Repository flatcar/scripts, pull requests merged in 2021-12, with the labels that each got.

#188 jenkins: make release.sh publish arm64 for Beta
  changelog/bugfixes/2021-12-09-jenkins-arm64-beta.md
  jenkins/release.sh
Labels: bug, alpha, beta

#189 jenkins: make release.sh publish arm64 for Stable
  changelog/bugfixes/2021-12-10-jenkins-arm64-stable.md
  jenkins/release.sh
Labels: alpha, beta, main

#194 *: Replace kinvolk github org with flatcar-linux
  bootstrap_sdk
  build_library/build_image_util.sh
  build_library/dev_container_util.sh
  changelog/bugfixes/2021-12-22-fix-dev-container.md
Labels: alpha, lts, beta, stable, main
