Repository flatcar/scripts, pull requests merged in 2023-05, with the labels that each got.

#749 .github: get build and CI triggered by opened, synchronize
  .github/workflows/cacerts-release.yaml
  .github/workflows/ci.yaml
  .github/workflows/containerd-release-main.yaml
  .github/workflows/docker-release-main.yaml
  .github/workflows/firmware-release-main.yaml
  .github/workflows/go-release-main.yaml
  .github/workflows/kernel-release.yaml
  .github/workflows/mantle-releases-main.yml
  .github/workflows/runc-release-main.yaml
  .github/workflows/rust-release-main.yaml
  .github/workflows/update-metadata-glsa.yaml
  .github/workflows/vmware-release-main.yaml
Labels: github-actions

#773 Monthly GLSA metadata 2023-05-02
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
Labels: main

#742 build_library: Split `base_image_var.conf` into two config files
  build_library/build_image_util.sh
  build_library/gen_tmpfiles.py
Labels: main

#748 update_chroot: Fix some non-fatal error noise
  build_library/update_chroot_util.sh
  update_chroot
Labels: main

#784 .github: check remote branch, add correct changelog
  .github/workflows/cacerts-apply-patch.sh
  .github/workflows/cacerts-release.yaml
  .github/workflows/ci.yaml
  .github/workflows/common.sh
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/containerd-release-main.yaml
  .github/workflows/docker-apply-patch.sh
  .github/workflows/docker-release-main.yaml
  .github/workflows/firmware-apply-patch.sh
  .github/workflows/firmware-release-main.yaml
  .github/workflows/go-apply-patch.sh
  .github/workflows/go-release-main.yaml
  .github/workflows/kernel-apply-patch.sh
  .github/workflows/kernel-release.yaml
  .github/workflows/runc-apply-patch.sh
  .github/workflows/runc-release-main.yaml
  .github/workflows/rust-apply-patch.sh
  .github/workflows/rust-release-main.yaml
  .github/workflows/vmware-apply-patch.sh
  .github/workflows/vmware-release-main.yaml
Labels: github-actions

#786 Upgrade Go from 1.19.8 to 1.19.9
  changelog/security/2023-05-03-go-1.19.9.md
  changelog/updates/2023-05-03-go-1.19.9-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.19.9.ebuild
Labels: main

#785 net-dns/c-ares: update to 1.19
  .github/workflows/portage-stable-packages-list
  changelog/security/2023-05-03-c-ares-1.19.0.md
  changelog/updates/2023-05-03-c-ares-1.19.0.md
  sdk_container/src/third_party/portage-stable/net-dns/c-ares/Manifest
  sdk_container/src/third_party/portage-stable/net-dns/c-ares/c-ares-1.17.1.ebuild
  sdk_container/src/third_party/portage-stable/net-dns/c-ares/c-ares-1.19.0.ebuild
  sdk_container/src/third_party/portage-stable/net-dns/c-ares/metadata.xml
Labels: main

#788 Upgrade Runc in main from 1.1.6 to 1.1.7
  changelog/updates/2023-05-04-runc-1.1.7-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-runc/Manifest
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-runc/docker-runc-1.1.7.ebuild
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
Labels: main

#790 .github: check for remote branches with git ls-remote
  .github/workflows/common.sh
Labels: github-actions

#798 Update ca-certificates in main from 3.89 to 3.89.1
  changelog/updates/2023-05-08-ca-certificates-3.89.1-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.89.1.ebuild
Labels: main

#794 Update ca-certificates in flatcar-3033 from 3.89 to 3.89.1
  changelog/updates/2023-05-08-ca-certificates-3.89.1-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.89.1.ebuild
Labels: lts

#795 Update ca-certificates in flatcar-3572 from 3.89 to 3.89.1
  changelog/updates/2023-05-08-ca-certificates-3.89.1-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.89.1.ebuild
Labels: alpha

#796 Update ca-certificates in flatcar-3549 from 3.89 to 3.89.1
  changelog/updates/2023-05-08-ca-certificates-3.89.1-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.89.1.ebuild
Labels: beta

#797 Update ca-certificates in flatcar-3510 from 3.89 to 3.89.1
  changelog/updates/2023-05-08-ca-certificates-3.89.1-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.89.1.ebuild
Labels: stable

#775 net-misc/openssh: update to 9.3
  changelog/security/2023-05-03-openssh-9.3.md
  changelog/updates/2023-05-03-openssh-9.3.md
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/Manifest
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/files/openssh-8.0_p1-deny-shmget-shmat-shmdt-in-preauth-privsep-child.patch
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/files/openssh-9.3_p1-deny-shmget-shmat-shmdt-in-preauth-privsep-child.patch
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/files/openssh-9.3_p1-openssl-version-compat-check.patch
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/openssh-9.3_p1.ebuild
Labels: main

#787 dev-libs/openssl: update to 3.0.8-r4
  changelog/security/2023-05-04-openssl-3.0.8-r4.md
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-0464.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-0465.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-0466.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-1255.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-mips-cflags.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/openssl-3.0.8-r4.ebuild
Labels: main

#809 sys-apps/acl: Sync with Gentoo to fix crash
  .github/workflows/portage-stable-packages-list
  changelog/bugfixes/2023-05-10-getfacl-coredump.md
  sdk_container/src/third_party/portage-stable/sys-apps/acl/Manifest
  sdk_container/src/third_party/portage-stable/sys-apps/acl/acl-2.3.1-r1.ebuild
  sdk_container/src/third_party/portage-stable/sys-apps/acl/metadata.xml
Labels: alpha, beta, main

#813 app-emulation/containerd: Upgrade Containerd from 1.6.20 to 1.6.21
  changelog/updates/2023-05-11-containerd-1.6.21-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-emulation/containerd/containerd-1.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
Labels: main

#815 Upgrade Linux Kernel for main from 5.15.108 to 5.15.111
  changelog/updates/2023-05-12-linux-5.15.111-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.111.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.111.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.111.ebuild
Labels: main

#816 Upgrade Linux Kernel for flatcar-3572 from 5.15.108 to 5.15.111
  changelog/updates/2023-05-12-linux-5.15.111-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.111.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.111.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.111.ebuild
Labels: alpha

#818 Upgrade Linux Kernel for flatcar-3549 from 5.15.108 to 5.15.111
  changelog/updates/2023-05-12-linux-5.15.111-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.111.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.111.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.111.ebuild
Labels: beta

#812 Automate updates of system packages: net-*
  .github/workflows/portage-stable-packages-list
  changelog/updates/2023-05-17-sys-packages-net-glob.md
  sdk_container/src/third_party/portage-stable/net-firewall/ipset/Manifest
  sdk_container/src/third_party/portage-stable/net-firewall/ipset/files/ipset-7.16-bashism.patch
  sdk_container/src/third_party/portage-stable/net-firewall/ipset/files/ipset-7.4-fix-pkgconfig-dir.patch
  sdk_container/src/third_party/portage-stable/net-firewall/ipset/files/ipset.systemd-r1
  sdk_container/src/third_party/portage-stable/net-firewall/ipset/ipset-7.11-r1.ebuild
  sdk_container/src/third_party/portage-stable/net-firewall/ipset/ipset-7.17.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libnftnl/Manifest
  sdk_container/src/third_party/portage-stable/net-libs/libnftnl/libnftnl-1.2.4.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libnftnl/libnftnl-1.2.5.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libnftnl/libnftnl-9999.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libnftnl/metadata.xml
  sdk_container/src/third_party/portage-stable/net-nds/rpcbind/metadata.xml
  sdk_container/src/third_party/portage-stable/net-nds/rpcbind/rpcbind-1.2.6.ebuild
Labels: main

#810 sys-kernel/*: Bump to kernel 6.1.27
  changelog/updates/2023-05-11-kernel-6.1.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-proxy/Manifest
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-proxy/docker-proxy-0.8.0_p20210525.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-proxy/docker-proxy-0.8.0_p20230118.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-proxy/metadata.xml
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker/docker-20.10.24-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker/metadata.xml
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.27.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.27.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/amd64_defconfig-6.1
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/arm64_defconfig-6.1
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.1
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.27.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/5.15/z0002-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/5.15/z0003-PCI-hv-Make-the-code-arch-neutral-by-adding-arch-spe.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/5.15/z0004-PCI-hv-Add-arm64-Hyper-V-vPCI-support.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/5.15/z0005-Drivers-hv-vmbus-Propagate-VMbus-coherence-to-each-V.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/5.15/z0006-PCI-hv-Avoid-the-retarget-interrupt-hypercall-in-irq.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/5.15/z0007-PCI-hv-Remove-unused-hv_set_msi_entry_from_desc.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.1/z0001-kbuild-derive-relative-path-for-srctree-from-CURDIR.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.1/z0002-Revert-scripts-pahole-flags.sh-Parse-DWARF-and-gener.patch
Labels: main

#825 Upgrade Linux Firmware in main from 20230404 to 20230515
  changelog/updates/2023-05-18-linux-firmware-20230515-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20230515.ebuild
Labels: main

#817 Upgrade Linux Kernel for flatcar-3510 from 5.15.108 to 5.15.111
  changelog/updates/2023-05-12-linux-5.15.111-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.111.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.111.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.111.ebuild
Labels: stable, on-hold

#841 Upgrade Linux Kernel for flatcar-3602 from 5.15.111 to 5.15.113
  changelog/updates/2023-05-25-linux-5.15.113-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.113.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.113.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.113.ebuild
Labels: alpha

#843 Upgrade Linux Kernel for flatcar-3572 from 5.15.111 to 5.15.113
  changelog/updates/2023-05-25-linux-5.15.113-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.113.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.113.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.113.ebuild
Labels: beta

#842 Upgrade Linux Kernel for main from 6.1.27 to 6.1.30
  changelog/updates/2023-05-25-linux-6.1.30-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.30.ebuild
Labels: main
