Repository flatcar/scripts, pull requests merged in 2023-07, with the labels that each got.

#950 Use zstd for sdk container images
  .github/workflows/ci.yaml
  .github/workflows/run-kola-tests.yaml
  .github/workflows/setup-flatcar-sdk.sh
  .github/workflows/update-sdk.yaml
  ci-automation/ci-config.env
  ci-automation/ci_automation_common.sh
Labels: main

#962 Upgrade Linux Kernel for main from 6.1.34 to 6.1.37
  changelog/updates/2023-07-02-linux-6.1.37-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.37.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.37.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.37.ebuild
Labels: main

#965 Update ca-certificates in flatcar-3602 from 3.90 to 3.91
  changelog/updates/2023-07-03-ca-certificates-3.91-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.91.ebuild
Labels: beta

#966 Update ca-certificates in flatcar-3637 from 3.90 to 3.91
  changelog/updates/2023-07-03-ca-certificates-3.91-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.91.ebuild
Labels: alpha

#967 Update ca-certificates in flatcar-3510 from 3.90 to 3.91
  changelog/updates/2023-07-03-ca-certificates-3.91-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.91.ebuild
Labels: stable

#968 Update ca-certificates in flatcar-3033 from 3.90 to 3.91
  changelog/updates/2023-07-03-ca-certificates-3.91-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.91.ebuild
Labels: lts

#955 Upgrade Linux Kernel for flatcar-3033 from 5.10.184 to 5.10.186
  changelog/updates/2023-06-29-linux-5.10.186-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.186.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.186.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.186.ebuild
Labels: lts

#954 Upgrade Linux Kernel for flatcar-3602 from 5.15.117 to 5.15.119
  changelog/updates/2023-06-29-linux-5.15.119-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.119.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.119.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.119.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/5.15/z0006-PCI-hv-Avoid-the-retarget-interrupt-hypercall-in-irq.patch
Labels: beta

#960 Monthly GLSA metadata 2023-07-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
Labels: main

#969 Use `build_sysext` for building OEM sysext images, drop old stuff
  build_library/oem_sysext_util.sh
  build_library/vm_image_util.sh
  build_oem_sysext
  build_sysext
  ci-automation/vms.sh
  common.sh
  image_to_vm.sh
Labels: main

#971 Drop niftycloud and interoute OEM support
  build_library/disk_layout.json
  build_library/niftycloud_ovf.sh
  build_library/template_interoute.ovf
  build_library/vm_image_util.sh
  changelog/changes/2023-07-05-drop-niftycloud-and-interoute.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-interoute/files/cloud-config.yml
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-interoute/files/cloudstack-coreos-cloudinit
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-interoute/files/cloudstack-set-guest-password
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-interoute/files/cloudstack-ssh-key
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-interoute/files/flatcar-setup-environment
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-interoute/files/grub.cfg
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-interoute/oem-interoute-0.0.3-r2.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-niftycloud/files/cloud-config.yml
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-niftycloud/files/flatcar-setup-environment
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-niftycloud/files/grub.cfg
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-niftycloud/files/niftycloud-coreos-cloudinit
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-niftycloud/files/niftycloud-ssh-key
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-niftycloud/metadata.xml
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-niftycloud/oem-niftycloud-0.0.3-r2.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0001-sed-s-coreos-flatcar.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0002-mod-add-flatcar-ignition-0.36.2.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0003-sum-go-mod-tidy.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0004-vendor-go-mod-vendor.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0005-config-add-ignition-translation.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0006-config-v3_5-convert-ignition-2.x-to-3.x.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0007-internal-prv-cmdline-backport-flatcar-patch.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0008-provider-qemu-apply-fw_cfg-patch.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0009-config-3_5-test-add-ignition-2.x-test-cases.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0010-internal-disk-fs-ignore-fs-format-mismatches-for-the.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0011-VMware-Fix-guestinfo.-.config.data-and-.config.url-v.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0012-config-version-handle-configuration-version-1.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0013-config-util-add-cloud-init-detection-to-initial-pars.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0014-Revert-drop-OEM-URI-support.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0015-internal-resource-url-support-btrfs-as-OEM-partition.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0016-internal-exec-stages-disks-prevent-races-with-udev.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0017-translation-support-OEM-and-oem.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0018-revert-internal-oem-drop-noop-OEMs.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0019-docs-Add-re-added-platforms-to-docs-to-pass-tests.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0020-usr-share-oem-oem.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0021-internal-exec-stages-mount-Mount-oem.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/ignition-2.15.0-r3.ebuild
Labels: main

#972 Drop a random file
  dev/null
Labels: main

#899 Upgrade Containerd in main from 1.6.21 to 1.7.2
  changelog/updates/2023-06-09-containerd-1.7.2-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.2.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/files/config-cgroupfs.toml
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/files/config.toml
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
Labels: main

#974 Upgrade Linux Firmware in main from 20230515 to 20230625
  changelog/updates/2023-07-06-linux-firmware-20230625-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20230625.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
Labels: main

#986 dev-libs/protobuf: update to 21.9
  .github/workflows/portage-stable-packages-list
  changelog/security/2023-07-13-protobuf-21.9.md
  changelog/updates/2023-07-13-protobuf-21.9.md
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/Manifest
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/files/protobuf-21.9-disable-32-bit-tests.patch
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/files/protobuf-3.17.0-disable_no-warning-test.patch
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/files/protobuf-3.17.0-system_libraries.patch
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/files/protobuf-3.18.0-disable_no-warning-test.patch
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/files/protobuf-3.18.0-system_libraries.patch
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/files/protobuf-3.20.2-protoc_input_output_files.patch
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/protobuf-21.9.ebuild
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/protobuf-3.17.0.ebuild
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/protobuf-3.17.1.ebuild
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/protobuf-3.17.2.ebuild
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/protobuf-3.17.3.ebuild
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/protobuf-3.19.1.ebuild
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/protobuf-3.19.3.ebuild
  sdk_container/src/third_party/portage-stable/dev-libs/protobuf/protobuf-9999.ebuild
Labels: main

#975 Upgrade Linux Kernel for main from 6.1.37 to 6.1.38
  changelog/updates/2023-07-06-linux-6.1.38-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.38.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.38.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.38.ebuild
Labels: main

#977 Upgrade Linux Kernel for flatcar-3602 from 5.15.119 to 5.15.120
  changelog/updates/2023-07-06-linux-5.15.120-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.120.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.120.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.120.ebuild
Labels: beta

#980 Upgrade Linux Kernel for flatcar-3654 from 6.1.37 to 6.1.38
  changelog/updates/2023-07-07-linux-6.1.38-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.38.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.38.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.38.ebuild
Labels: alpha

#989 ci-automation/vms: Export official release variable
  .gitignore
  ci-automation/vms.sh
Labels: alpha, main, flatcar-3665

#981 Upgrade Linux Kernel for flatcar-3510 from 5.15.119 to 5.15.120
  changelog/updates/2023-07-07-linux-5.15.120-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.120.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.120.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.120.ebuild
Labels: stable

#990 Upgrade dev-lang/rust and virtual/rust in main from 1.70.0 to 1.71.0
  changelog/updates/2023-07-18-rust-1.71.0-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.71.0.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.71.0.ebuild
Labels: main

#998 Upgrade Runc in main from 1.1.7 to 1.1.8
  changelog/updates/2023-07-20-runc-1.1.8-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/runc-1.1.8.ebuild
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
Labels: main

#988 Upgrade Go from 1.19.10 and 1.20.5 to 1.19.11 and 1.20.6
  changelog/security/2023-07-17-go-1.19.11-1.20.6.md
  changelog/updates/2023-07-17-go-1.19.11-update.md
  changelog/updates/2023-07-17-go-1.20.6-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-cli/docker-cli-20.10.24-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-cli/files/0001-20.10-vendor-docker-v20.10.25-45-g0d4b9ed98b-v20.10..patch
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/docker-20.10.24-r3.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/files/0001-client-define-a-dummy-hostname-to-use-for-local-conn.patch
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/files/0002-pkg-plugins-use-a-dummy-hostname-for-local-connectio.patch
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.19.11.ebuild
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.20.6.ebuild
Labels: main

#1009 Upgrade Linux Kernel for flatcar-3510 from 5.15.120 to 5.15.122
  changelog/updates/2023-07-25-linux-5.15.122-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.122.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.122.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.122.ebuild
Labels: stable

#1022 net-misc/openssh: update to 9.3_p2
  changelog/security/2023-07-27-openssh-9.3_p2.md
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/Manifest
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/openssh-9.3_p2-r1.ebuild
Labels: alpha, beta, main

#1024 Upgrade Containerd in main from 1.7.2 to 1.7.3
  changelog/updates/2023-07-28-containerd-1.7.3-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.3.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
Labels: main

#1027 Update ca-certificates in main from 3.91 to 3.92
  changelog/updates/2023-07-31-ca-certificates-3.92-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.92.ebuild
Labels: main

#1026 Update ca-certificates in flatcar-3602 from 3.91 to 3.92
  changelog/updates/2023-07-31-ca-certificates-3.92-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.92.ebuild
Labels: beta

#1028 Update ca-certificates in flatcar-3665 from 3.91 to 3.92
  changelog/updates/2023-07-31-ca-certificates-3.92-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.92.ebuild
Labels: alpha

#1029 Update ca-certificates in flatcar-3510 from 3.91 to 3.92
  changelog/updates/2023-07-31-ca-certificates-3.92-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.92.ebuild
Labels: stable

#1030 Update ca-certificates in flatcar-3033 from 3.91 to 3.92
  changelog/updates/2023-07-31-ca-certificates-3.92-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.92.ebuild
Labels: lts
