Repository flatcar/scripts, pull requests merged in 2023-06, with the labels that each got.

#840 Upgrade Linux Kernel for flatcar-3510 from 5.15.111 to 5.15.113
  changelog/updates/2023-05-25-linux-5.15.113-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.113.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.113.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.113.ebuild
Labels: stable

#863 Move sys-process/tini from overlay to portage-stable
  .github/workflows/portage-stable-packages-list
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker/docker-20.10.24-r2.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/arm64/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/sys-process/tini/README.md
  sdk_container/src/third_party/coreos-overlay/sys-process/tini/files/automake/Makefile.am
  sdk_container/src/third_party/coreos-overlay/sys-process/tini/files/automake/configure.ac
  sdk_container/src/third_party/coreos-overlay/sys-process/tini/files/automake/src/Makefile.am
  sdk_container/src/third_party/coreos-overlay/sys-process/tini/tini-0.19.0-r1.ebuild
  sdk_container/src/third_party/portage-stable/sys-process/tini/Manifest
  sdk_container/src/third_party/portage-stable/sys-process/tini/metadata.xml
  sdk_container/src/third_party/portage-stable/sys-process/tini/tini-0.19.0-r1.ebuild
Labels: main

#872 app-admin/sudo: update to 1.9.13p3
  2023-06-02-sudo-1.9.13p3.md
  changelog/updates/2023-06-02-sudo-1.9.13p3-update.md
  sdk_container/src/third_party/coreos-overlay/app-admin/sudo/Manifest
  sdk_container/src/third_party/coreos-overlay/app-admin/sudo/sudo-1.9.13_p3.ebuild
Labels: main

#878 Update ca-certificates in main from 3.89 to 3.90
  changelog/updates/2023-06-05-ca-certificates-3.90-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.90.ebuild
Labels: main

#875 Update ca-certificates in flatcar-3619 from 3.89 to 3.90
  changelog/updates/2023-06-05-ca-certificates-3.90-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.90.ebuild
Labels: alpha

#876 Update ca-certificates in flatcar-3510 from 3.89 to 3.90
  changelog/updates/2023-06-05-ca-certificates-3.90-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.90.ebuild
Labels: stable

#877 Update ca-certificates in flatcar-3602 from 3.89 to 3.90
  changelog/updates/2023-06-05-ca-certificates-3.90-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.90.ebuild
Labels: beta

#889 Update ca-certificates in flatcar-3033 from 3.89 to 3.90
  changelog/updates/2023-06-06-ca-certificates-3.90-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.90.ebuild
Labels: lts

#864 Move docker packages from app-emulation to app-containers
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/docker-apply-patch.sh
  .github/workflows/runc-apply-patch.sh
  build_docker_aci
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/files/config-cgroupfs.toml
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/files/config.toml
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/files/containerd-1.0.0.service
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/files/containerd.service
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/metadata.xml
  sdk_container/src/third_party/coreos-overlay/app-containers/cri-tools/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/cri-tools/cri-tools-1.24.2.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/cri-tools/metadata.xml
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-cli/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-cli/docker-cli-20.10.24.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-cli/metadata.xml
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-proxy/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-proxy/docker-proxy-0.8.0_p20230118.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-proxy/metadata.xml
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/docker-20.10.24-r2.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/files/50-docker.network
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/files/90-docker-veth.network
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/files/docker.service
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/files/docker.socket
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/files/dockerd
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/files/ppc64-buildmode.patch
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/metadata.xml
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/files/0001-Delay-unshare-of-clone-newipc-for-selinux.patch
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/files/0001-nsenter-clone-proc-self-exe-to-avoid-exposing-host-b.patch
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/files/docker-runc-1.0.0_rc2-mount-propagation.patch
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/metadata.xml
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/runc-1.1.7.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-runc/Manifest
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos/coreos-0.0.1-r307.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos/coreos-0.0.1.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use
Labels: main

#892 sys-apps/systemd: Update to 252.11
  changelog/bugfixes/2023-06-07-systemd-reboot.md
  changelog/updates/2023-06-07-systemd-update.md
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/systemd-252.11.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-0.0.38-r16.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
Labels: main

#900 Upgrade Linux Kernel for flatcar-3619 from 6.1.30 to 6.1.33
  changelog/updates/2023-06-09-linux-6.1.33-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.33.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.33.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.33.ebuild
Labels: alpha

#901 Upgrade Linux Kernel for main from 6.1.30 to 6.1.33
  changelog/updates/2023-06-09-linux-6.1.33-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.33.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.33.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.33.ebuild
Labels: main

#893 Upgrade Go from 1.19.9 and 1.20.4 to 1.19.10 and 1.20.5
  changelog/security/2023-06-08-go-1.19.10-1.20.5.md
  changelog/updates/2023-06-08-go-1.19.10-update.md
  changelog/updates/2023-06-08-go-1.20.5-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.19.10.ebuild
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.20.5.ebuild
Labels: main

#916 Upgrade open-vm-tools in main from 12.2.0 to 12.2.5
  changelog/security/2023-06-14-open-vm-tools-12.2.5.md
  changelog/updates/2023-06-14-open-vm-tools-12.2.5-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/open-vm-tools/Manifest
  sdk_container/src/third_party/coreos-overlay/app-emulation/open-vm-tools/open-vm-tools-12.2.5.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-vmware/oem-vmware-12.2.5.ebuild
Labels: main

#907 overlay: Profile cleanups
  .github/workflows/portage-stable-packages-list
  changelog/security/2023-06-02-sudo-1.9.13p3.md
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/arm64/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.mask
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/sdk/package.accept_keywords
Labels: main

#866 Migrate to Type=notify
  changelog/changes/2023-06-15-containerd-service
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/files/containerd.service
Labels: main

#908 dev-lang/rust: Update to 1.70.0
  changelog/updates/2023-06-13-rust-1.70.0-update.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/afterburn-5.2.0-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/afterburn-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/files/0004-lto-thin.patch
  sdk_container/src/third_party/coreos-overlay/coreos-base/update-ssh-keys/update-ssh-keys-0.3.0-r7.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/files/1.70.0-ignore-broken-and-non-applicable-tests.patch
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.70.0.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.70.0.ebuild
Labels: main

#926 Upgrade Linux Kernel for flatcar-3033 from 5.10.180 to 5.10.184
  changelog/updates/2023-06-15-linux-5.10.184-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.184.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.184.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.184.ebuild
Labels: lts

#927 Upgrade Linux Kernel for main from 6.1.33 to 6.1.34
  changelog/updates/2023-06-15-linux-6.1.34-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.34.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.34.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.34.ebuild
Labels: main

#929 Upgrade Linux Kernel for flatcar-3602 from 5.15.113 to 5.15.117
  changelog/updates/2023-06-15-linux-5.15.117-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.117.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.117.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.117.ebuild
Labels: beta

#930 Upgrade Linux Kernel for flatcar-3619 from 6.1.33 to 6.1.34
  changelog/updates/2023-06-15-linux-6.1.34-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.34.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.34.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.34.ebuild
Labels: alpha

#937 coreos-base/coreos-cloudinit: Don't use configdrive on DigitalOcean
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
Labels: alpha, main

#928 Upgrade Linux Kernel for flatcar-3510 from 5.15.113 to 5.15.117
  changelog/updates/2023-06-15-linux-5.15.117-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.117.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.117.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.117.ebuild
Labels: stable

#939 Switch default ext4 inode size to 256 bytes
  build_library/disk_util
  changelog/changes/2023-06-22-ext4-inode-size.md
Labels: alpha, lts, beta, stable

#948 coreos-base/coreos-init: Work around bash regression and handle dd error
  changelog/bugfixes/2023-06-26-flatcar-install.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-0.0.1-r182.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: alpha, beta, main

#946 oem_sysext_util: Mount overlay on top of /usr before installing sysext
  build_library/oem_sysext_util.sh
  ci-automation/ci-config.env
  ci-automation/image.sh
  ci-automation/packages.sh
Labels: alpha, main

#938 dev-libs/openssl: update to 3.0.9
  changelog/security/2023-06-20-openssl-3.0.9.md
  changelog/updates/2023-06-20-openssl-3.0.9.md
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-0464.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-0465.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-0466.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-1255.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-mips-cflags.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/openssl-3.0.9.ebuild
Labels: main

#949 sys-auth/sssd: Add missing /var/log/sssd tmpfiles entry
  changelog/bugfixes/2023-06-28-sssd-var-log.md
  sdk_container/src/third_party/coreos-overlay/sys-auth/sssd/files/tmpfiles.d/sssd.conf
Labels: alpha, beta, main

#951 [acct-group/docker] Add acct-group/docker to portage-stable
  sdk_container/src/third_party/portage-stable/acct-group/docker/docker-0-r1.ebuild
  sdk_container/src/third_party/portage-stable/acct-group/docker/metadata.xml
Labels: main

#859 app-admin/locksmith: Stop using deprecated resource control options
  changelog/changes/2023-06-29-locksmith-cgroup.md
  sdk_container/src/third_party/coreos-overlay/app-admin/locksmith/locksmith-0.7.0-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/app-admin/locksmith/locksmith-9999.ebuild
Labels: main

#957 net-libs/libmicrohttpd: update to 0.9.76
  .github/workflows/portage-stable-packages-list
  changelog/security/2023-06-29-libmicrohttpd-0.9.76.md
  changelog/updates/2023-06-29-libmicrohttpd-0.9.76.md
  sdk_container/src/third_party/portage-stable/net-libs/libmicrohttpd/Manifest
  sdk_container/src/third_party/portage-stable/net-libs/libmicrohttpd/files/libmicrohttpd-0.9.73-test-ssl3.patch
  sdk_container/src/third_party/portage-stable/net-libs/libmicrohttpd/files/libmicrohttpd-0.9.75-fix-testsuite-with-lto.patch
  sdk_container/src/third_party/portage-stable/net-libs/libmicrohttpd/libmicrohttpd-0.9.68-r1.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libmicrohttpd/libmicrohttpd-0.9.72.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libmicrohttpd/libmicrohttpd-0.9.75.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libmicrohttpd/libmicrohttpd-0.9.76.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libmicrohttpd/libmicrohttpd-0.9.77.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libmicrohttpd/metadata.xml
Labels: main

#958 docker group fixes
  .github/workflows/portage-stable-packages-list
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/generic/make.defaults
Labels: main
