Repository flatcar/scripts, pull requests merged in 2023-12, with the labels that each got.

#1453 Monthly GLSA metadata 2023-12-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-07.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-08.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-09.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-10.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-11.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-12.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-13.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-14.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-15.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-16.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-17.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202311-18.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#1464 Update ca-certificates in main from 3.94 to 3.95
  changelog/updates/2023-12-04-ca-certificates-3.95-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.95.ebuild
Labels: main

#1461 Update ca-certificates in flatcar-3602 from 3.94 to 3.95
  changelog/updates/2023-12-04-ca-certificates-3.95-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.95.ebuild
Labels: stable

#1462 Update ca-certificates in flatcar-3033 from 3.94 to 3.95
  changelog/updates/2023-12-04-ca-certificates-3.95-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.95.ebuild
Labels: lts

#1463 Update ca-certificates in flatcar-3794 from 3.94 to 3.95
  changelog/updates/2023-12-04-ca-certificates-3.95-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.95.ebuild
Labels: alpha

#1469 overlay ue-rs: update to 0.1.0-r4, 2023-12-05
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-0.1.0-r4.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-9999.ebuild
Labels: main

#1471 Upgrade Linux Kernel for flatcar-3033 from 5.10.202 to 5.10.203
  changelog/updates/2023-12-09-linux-5.10.203-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.203.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.203.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.203.ebuild
Labels: lts

#1472 Upgrade Linux Kernel for flatcar-3602 from 5.15.141 to 5.15.142
  changelog/updates/2023-12-09-linux-5.15.142-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.142.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.142.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.142.ebuild
Labels: stable

#1473 Upgrade Linux Kernel for flatcar-3510 from 5.15.141 to 5.15.142
  changelog/updates/2023-12-09-linux-5.15.142-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.142.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.142.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.142.ebuild
Labels: lts

#1474 Upgrade Linux Kernel for flatcar-3760 from 6.1.65 to 6.1.66
  changelog/updates/2023-12-09-linux-6.1.66-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.66.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.66.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.66.ebuild
Labels: beta

#1475 Upgrade Linux Kernel for flatcar-3794 from 6.1.65 to 6.1.66
  changelog/updates/2023-12-09-linux-6.1.66-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.66.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.66.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.66.ebuild
Labels: alpha

#1476 Upgrade Linux Kernel for main from 6.1.65 to 6.1.66
  changelog/updates/2023-12-09-linux-6.1.66-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.66.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.66.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.66.ebuild
Labels: main

#1157 overlay profiles: Fix a couple of issues with SLSA provenance stuff
  changelog/changes/2023-09-20-slsa.md
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/profile.bashrc.slsa-provenance
Labels: main

#1483 Upgrade Linux Firmware in main from 20231111 to 20231211
  changelog/updates/2023-12-14-linux-firmware-20231211-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20231211.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
Labels: main
