Repository flatcar/scripts, pull requests merged in 2023-08, with the labels that each got.

#1036 Monthly GLSA metadata 2023-08-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202307-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#1037 dev-libs/openssl, sys-apps/shadow: Security updates
  changelog/security/2023-08-01-openssl-shadow.md
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/gentoo.config-1.0.4
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.9-CVE-2023-2975.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.9-CVE-2023-3446.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/openssl-3.0.9-r2.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-apps/shadow/files/shadow-4.1.3-dots-in-usernames.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/shadow/files/shadow-4.13-CVE-2023-29383.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/shadow/files/shadow-4.13-password-leak.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/shadow/files/shadow-4.13-usermod-prefix-gid.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/shadow/shadow-4.13-r4.ebuild
Labels: main

#1041 Upgrade Go from 1.19.11 and 1.20.6 to 1.19.12 and 1.20.7
  changelog/security/2023-08-02-go-1.19.12-1.20.7.md
  changelog/updates/2023-08-02-go-1.19.12-update.md
  changelog/updates/2023-08-02-go-1.20.7-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.19.12.ebuild
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.20.7.ebuild
Labels: main

#1039 overlay sys-kernel/coreos-firmware: update to 20230625_p20230724 for flatcar-3665
  changelog/security/2023-08-01-linux-firmware-20230625_p20230724.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20230625_p20230724.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
Labels: alpha, lts, beta, stable, flatcar-3033, flatcar-3665, flatcar-3510, flatcar-3602

#1040 overlay sys-kernel/coreos-firmware: update to 20230625_p20230724 for main
  changelog/security/2023-08-01-linux-firmware-20230625_p20230724.md
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/make.defaults
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20230625_p20230724.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
Labels: main

#1045 Upgrade Linux Kernel for flatcar-3602 from 5.15.120 to 5.15.124
  changelog/updates/2023-08-03-linux-5.15.124-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.124.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.124.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.124.ebuild
Labels: beta

#1017 Upgrade Linux Kernel for flatcar-3033 from 5.10.186 to 5.10.188
  changelog/updates/2023-07-27-linux-5.10.188-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.188.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.188.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.188.ebuild
Labels: lts

#1044 Upgrade Linux Kernel for main from 6.1.38 to 6.1.43
  changelog/updates/2023-08-03-linux-6.1.43-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.43.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.43.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.43.ebuild
Labels: main

#1043 Upgrade Linux Kernel for flatcar-3665 from 6.1.38 to 6.1.43
  changelog/updates/2023-08-03-linux-6.1.43-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.43.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.43.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.43.ebuild
Labels: alpha

#1048 Upgrade dev-lang/rust and virtual/rust in main from 1.71.0 to 1.71.1
  changelog/security/2023-08-03-rust-1.71.1.md
  changelog/updates/2023-08-03-rust-1.71.1-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.71.1.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.71.1.ebuild
Labels: alpha, main

#1055 Upgrade Linux Firmware in main from 20230625 to 20230804
  changelog/updates/2023-08-10-linux-firmware-20230804-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20230804.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
Labels: main

#1057 ci-automation: explicitly make packages tarballs readable
  ci-automation/ci_automation_common.sh
Labels: bug, alpha, main

#1071 overlay sys-kernel/coreos-firmware: regenerate Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
Labels: bug, main

#1059 net-nds/openldap: update to 2.6.3
  changelog/updates/2023-08-11-openldap-2.6.3.md
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.mask
Labels: main

#1072 Upgrade Runc in main from 1.1.8 to 1.1.9
  changelog/updates/2023-08-15-runc-1.1.9-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/runc/runc-1.1.9.ebuild
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
Labels: main

#1052 Upgrade Linux Kernel for flatcar-3510 from 5.15.124 to 5.15.125
  changelog/security/2023-08-09-linux-5.15.125.md
  changelog/updates/2023-08-09-linux-5.15.125-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.125.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.125.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.125.ebuild
Labels: stable

#1065 Upgrade Linux Kernel for flatcar-3602 from 5.15.124 to 5.15.126
  changelog/security/2023-08-09-linux-5.15.125.md
  changelog/updates/2023-08-12-linux-5.15.126-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.126.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.126.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.126.ebuild
Labels: beta

#1084 Upgrade Containerd in main from 1.7.3 to 1.7.4
  changelog/updates/2023-08-25-containerd-1.7.4-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.4.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
Labels: main

#1093 Upgrade Containerd in main from 1.7.4 to 1.7.5
  changelog/updates/2023-08-29-containerd-1.7.5-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.5.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
Labels: main

#1094 Upgrade dev-lang/rust and virtual/rust in main from 1.71.1 to 1.72.0
  changelog/updates/2023-08-29-rust-1.72.0-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.72.0.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.72.0.ebuild
Labels: main
