Repository flatcar/scripts, pull requests merged in 2023-10, with the labels that each got.

#1191 net-fs/samba: update to 4.18.4
  changelog/security/2023-09-25-samba-4.18.4.md
  changelog/updates/2023-09-25-samba-4.18.4.md
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/Manifest
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/files/ldb-2.5.2-skip-wav-tevent-check.patch
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/files/samba-4.18.4-bug-15418-windows-update-secure-channel.patch
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/files/samba-4.18.4-pam.patch
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/files/samba.conf
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/metadata.xml
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/samba-4.18.4.ebuild
Labels: main

#1203 Monthly GLSA metadata 2023-10-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-07.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-08.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-09.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-10.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-11.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-12.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-13.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-14.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-15.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-16.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202309-17.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#1205 prefix: remove gcc-13 mask as the SDK now uses gcc-13
  sdk_container/src/third_party/prefix-overlay/skel/etc/portage/package.mask/cross
Labels: main

#1174 Upgrade Linux Kernel for flatcar-3510 from 5.15.132 to 5.15.133
  changelog/updates/2023-09-24-linux-5.15.133-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.133.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.133.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-5.15
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.133.ebuild
Labels: lts

#1227 Update ca-certificates in main from 3.93 to 3.94
  changelog/updates/2023-10-09-ca-certificates-3.94-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.94.ebuild
Labels: main

#1224 Update ca-certificates in flatcar-3033 from 3.93 to 3.94
  changelog/updates/2023-10-09-ca-certificates-3.94-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.94.ebuild
Labels: lts

#1225 Update ca-certificates in flatcar-3602 from 3.93 to 3.94
  changelog/updates/2023-10-09-ca-certificates-3.94-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.94.ebuild
Labels: stable

#1226 Update ca-certificates in flatcar-3510 from 3.93 to 3.94
  changelog/updates/2023-10-09-ca-certificates-3.94-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.94.ebuild
Labels: lts

#1228 Update ca-certificates in flatcar-3745 from 3.93 to 3.94
  changelog/updates/2023-10-09-ca-certificates-3.94-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.94.ebuild
Labels: alpha

#1229 Update ca-certificates in flatcar-3732 from 3.93 to 3.94
  changelog/updates/2023-10-09-ca-certificates-3.94-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.94.ebuild
Labels: beta

#1231 Build docker with go 1.19
  changelog/bugfixes/2023-10-09-docker-go-1.19.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-cli/docker-cli-20.10.24.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-proxy/docker-proxy-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker-runc/docker-runc-1.1.7.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/docker/docker-20.10.24.ebuild
Labels: stable

#1199 ci-automation: Switch to managed identity on azure
  ci-automation/garbage_collect_cloud.sh
  ci-automation/vendor-testing/azure.sh
Labels: alpha, lts, beta, stable

#1247 ci-automation: Update the SDK container extension in check
  ci-automation/sdk_bootstrap.sh
Labels: main

#1239 sys-libs/glibc: Update to 2.37-r7
  changelog/security/2023-10-10-glibc-update.md
  sdk_container/src/third_party/coreos-overlay/sys-libs/glibc/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-libs/glibc/glibc-2.37-r7.ebuild
Labels: main

#1206 systemd-networkd: disable RoutesToDNS
  changelog/bugfixes/2023-10-04-azure-multinic.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-0.0.1-r189.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-0.0.38-r22.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
Labels: bug, alpha, beta, stable, main

#1256 net-misc/openssh: Update to 9.5p1
  changelog/updates/2023-10-11-openssh-update.md
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/Manifest
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/files/openssh-9.3_p2-zlib-1.3.patch
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/openssh-9.5_p1.ebuild
Labels: main

#1264 overlay sys-boot/grub: Update to 2.06-r9
  changelog/security/2023-10-12-grub-update.md
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/files/grub-2.06-fs-ext2-ignore-checksum-seed.patch
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/files/grub-2.06-gentpl.py-Remove-.interp-section-from-.img-files.patch
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/files/grub-2.06-grub-mkconfig-restore-umask.patch
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/files/grub-2.06-locale.patch
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/files/grub-2.06-riscv.patch
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/files/grub-2.12_rc1-util-grub.d-25_bli.in-fix-shebang-on-unmerged-usr.patch
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/grub-2.06-r9.ebuild
Labels: main

#1248 Upgrade Linux Kernel for flatcar-3510 from 5.15.133 to 5.15.135
  changelog/updates/2023-10-11-linux-5.15.135-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.135.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.135.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.135.ebuild
Labels: lts

#1249 Upgrade Linux Kernel for flatcar-3033 from 5.10.197 to 5.10.198
  changelog/updates/2023-10-11-linux-5.10.198-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.198.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.198.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.198.ebuild
Labels: lts

#1250 Upgrade Linux Kernel for main from 6.1.55 to 6.1.57
  changelog/updates/2023-10-11-linux-6.1.57-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.57.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.57.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.57.ebuild
Labels: main

#1251 Upgrade Linux Kernel for flatcar-3732 from 6.1.55 to 6.1.57
  changelog/updates/2023-10-11-linux-6.1.57-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.57.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.57.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.57.ebuild
Labels: beta

#1252 Upgrade Linux Kernel for flatcar-3602 from 5.15.133 to 5.15.135
  changelog/updates/2023-10-11-linux-5.15.135-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.135.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.135.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.135.ebuild
Labels: stable

#1253 Upgrade Linux Kernel for flatcar-3745 from 6.1.55 to 6.1.57
  changelog/updates/2023-10-11-linux-6.1.57-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.57.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.57.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.57.ebuild
Labels: alpha

#1267 build_library/grub_install: Try mounting ESP directory in a loop
  build_library/grub_install.sh
Labels: main

#1263 Upgrade Go from 1.20.9 to 1.20.10
  changelog/security/2023-10-12-go-1.20.10-update.md
  changelog/updates/2023-10-12-go-1.20.10-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.20.10.ebuild
Labels: main

#1255 net-libs/libtirpc: Update to 1.3.4
  changelog/security/2023-10-11-libtirpc-update.md
  changelog/updates/2023-10-11-libtirpc-update.md
  sdk_container/src/third_party/coreos-overlay/net-libs/libtirpc/Manifest
  sdk_container/src/third_party/coreos-overlay/net-libs/libtirpc/files/libtirpc-1.3.2-dos.patch
  sdk_container/src/third_party/coreos-overlay/net-libs/libtirpc/files/libtirpc-1.3.2-memory-leak.patch
  sdk_container/src/third_party/coreos-overlay/net-libs/libtirpc/files/libtirpc-1.3.2-use-after-free.patch
  sdk_container/src/third_party/coreos-overlay/net-libs/libtirpc/libtirpc-1.3.4.ebuild
Labels: main

#1271 Backport curl CVE fixes to alpha
  changelog/security/2023-10-13-curl-backport.md
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/CVE-2023-38545_8.2.0.patch
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/CVE-2023-38546.patch
Labels: alpha

#1269 Backport curl CVE fixes to stable
  changelog/security/2023-10-13-curl-backport.md
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/CVE-2023-38545_7.87.0.patch
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/CVE-2023-38546.patch
Labels: stable

#1268 Upgrade Containerd in main from 1.7.6 to 1.7.7
  changelog/updates/2023-10-13-containerd-1.7.7-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.7.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-torcx/docker/docker-20.10.ebuild
Labels: main

#1272 update_engine/bootengine: Clean up incomplete move target
  changelog/bugfixes/2023-10-13-update-postinstall-cleanup.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-0.4.10-r14.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-0.0.38-r23.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
Labels: bug, alpha, beta

#1275 Upgrade Linux Kernel for main from 6.1.57 to 6.1.58
  changelog/updates/2023-10-16-linux-6.1.58-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.58.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.58.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.58.ebuild
Labels: main

#1273 Upgrade Linux Kernel for flatcar-3745 from 6.1.57 to 6.1.58
  changelog/updates/2023-10-16-linux-6.1.58-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.58.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.58.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.58.ebuild
Labels: alpha

#1274 Upgrade Linux Kernel for flatcar-3732 from 6.1.57 to 6.1.58
  changelog/updates/2023-10-16-linux-6.1.58-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.58.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.58.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.58.ebuild
Labels: beta

#1281 overlay dev-lang/rust: Update to 1.73.0
  changelog/updates/2023-10-17-rust-1.73.0-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/files/1.72.0-bump-libc-deps-to-0.2.146.patch
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/metadata.xml
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.73.0.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.73.0.ebuild
  sdk_container/src/third_party/portage-stable/eclass/rust-toolchain.eclass
Labels: main

#1170 disk_layout: use btrfs for the /usr partition
  build_library/disk_layout.json
Labels: main

#1313 overlay update-ssh-keys: update openssh-keys to 0.6.2
  sdk_container/src/third_party/coreos-overlay/coreos-base/update-ssh-keys/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/update-ssh-keys/files/0001-eclass-trick.patch
  sdk_container/src/third_party/coreos-overlay/coreos-base/update-ssh-keys/update-ssh-keys-0.3.0-r8.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild
Labels: main

#1314 overlay ue-rs: update to 0.1.0-r2, 2023-10-25
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-0.1.0-r2.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-9999.ebuild
Labels: main
