Repository flatcar/scripts, pull requests merged in 2023-11, with the labels that each got.

#1324 overlay net-fs/samba: Update to 4.18.8
  changelog/security/2023-11-01-samba-update.md
  changelog/updates/2023-11-01-samba-update.md
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/Manifest
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/files/samba-4.18.4-bug-15418-windows-update-secure-channel.patch
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/samba-4.18.8.ebuild
Labels: main

#1306 run_sdk_container: Clean up a bit and add mounting of custom volumes
  run_sdk_container
  sdk_lib/sdk_container_common.sh
Labels: main

#1329 Upgrade Linux Kernel for main from 6.1.60 to 6.1.61
  changelog/updates/2023-11-03-linux-6.1.61-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.61.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.61.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.61.ebuild
Labels: main

#1328 Upgrade Linux Kernel for flatcar-3760 from 6.1.60 to 6.1.61
  changelog/updates/2023-11-03-linux-6.1.61-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.61.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.61.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.61.ebuild
Labels: alpha

#1327 Upgrade Linux Kernel for flatcar-3745 from 6.1.60 to 6.1.61
  changelog/updates/2023-11-03-linux-6.1.61-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.61.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.61.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.61.ebuild
Labels: beta

#1325 Upgrade Linux Firmware in main from 20230919 to 20231030
  changelog/updates/2023-11-02-linux-firmware-20231030-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20231030.ebuild
Labels: main

#1336 Upgrade Containerd in main from 1.7.7 to 1.7.8
  changelog/updates/2023-11-03-containerd-1.7.8-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.8.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main

#1319 Monthly GLSA metadata 2023-11-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-07.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-08.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-09.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-10.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-11.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-12.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-13.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-14.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-15.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-16.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-17.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-18.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-19.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-20.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-21.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-22.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202310-23.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#1368 Upgrade Linux Kernel for flatcar-3760 from 6.1.61 to 6.1.62
  changelog/updates/2023-11-09-linux-6.1.62-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.62.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.62.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.62.ebuild
Labels: alpha

#1370 Upgrade Linux Kernel for flatcar-3602 from 5.15.137 to 5.15.138
  changelog/updates/2023-11-09-linux-5.15.138-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.138.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.138.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.138.ebuild
Labels: stable

#1369 Upgrade Linux Kernel for flatcar-3510 from 5.15.137 to 5.15.138
  changelog/updates/2023-11-09-linux-5.15.138-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.138.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.138.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.138.ebuild
Labels: lts

#1365 Upgrade Linux Kernel for flatcar-3033 from 5.10.199 to 5.10.200
  changelog/updates/2023-11-09-linux-5.10.200-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.200.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.200.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.200.ebuild
Labels: lts

#1366 Upgrade Linux Kernel for main from 6.1.61 to 6.1.62
  changelog/updates/2023-11-09-linux-6.1.62-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.62.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.62.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.62.ebuild
Labels: main

#1393 overlay update-ssh-keys: fix number of arguments of clap4 options
  sdk_container/src/third_party/coreos-overlay/coreos-base/update-ssh-keys/update-ssh-keys-0.3.0-r9.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild
Labels: bug, main

#1397 overlay ue-rs: update to 0.1.0-r3, 2023-11-16
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-0.1.0-r3.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-9999.ebuild
Labels: main

#1411 Upgrade Linux Kernel for flatcar-3760 from 6.1.62 to 6.1.63
  changelog/updates/2023-11-21-linux-6.1.63-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.63.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.63.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.63.ebuild
Labels: alpha

#1413 Upgrade Linux Kernel for flatcar-3602 from 5.15.138 to 5.15.139
  changelog/updates/2023-11-21-linux-5.15.139-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.139.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.139.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.139.ebuild
Labels: stable

#1415 Upgrade Linux Kernel for flatcar-3745 from 6.1.62 to 6.1.63
  changelog/updates/2023-11-21-linux-6.1.63-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.63.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.63.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.63.ebuild
Labels: beta

#1417 changelog: improved messaging for torcx removal and docker 24 upgrade
  changelog/changes/2023-10-19-torcx-removal.md
  changelog/changes/2023-10-25-docker-gentoo-upstream.md
Labels: alpha, main

#1169 Generate reports for OEM and base sysext images, allow reports against last nightly
  .github/workflows/ci.yaml
  .github/workflows/image_changes.sh
  ci-automation/base_sysexts.sh
  ci-automation/image.sh
  ci-automation/image_changes.sh
  sdk_container/src/third_party/coreos-overlay/coreos-base/common-oem-files/common-oem-files-0-r4.ebuild
Labels: main

#1425 ci-automation/image-changes: Get proper last release version for LTS channels
  ci-automation/image_changes.sh
Labels: main
