Repository flatcar/scripts, pull requests merged in 2024-01, with the labels that each got.

#1482 Upgrade dev-lang/rust and virtual/rust in main from 1.73.0 to 1.74.1
  changelog/updates/2023-12-12-rust-1.74.1-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.74.1.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.74.1.ebuild
Labels: main

#1532 Update ca-certificates in main from 3.96 to 3.96.1
  changelog/updates/2023-12-25-ca-certificates-3.96.1-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.96.1.ebuild
Labels: main

#1529 Update ca-certificates in flatcar-3760 from 3.96 to 3.96.1
  changelog/updates/2023-12-25-ca-certificates-3.96.1-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.96.1.ebuild
Labels: beta

#1530 Update ca-certificates in flatcar-3815 from 3.96 to 3.96.1
  changelog/updates/2023-12-25-ca-certificates-3.96.1-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.96.1.ebuild
Labels: alpha

#1533 Update ca-certificates in flatcar-3602 from 3.96 to 3.96.1
  changelog/updates/2023-12-25-ca-certificates-3.96.1-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.96.1.ebuild
Labels: stable

#1519 Upgrade Linux Kernel for main from 6.6.7 to 6.6.8
  changelog/updates/2023-12-21-linux-6.6.8-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.8.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.8.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.6
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.8.ebuild
Labels: main

#1542 Upgrade dev-lang/rust and virtual/rust in main from 1.74.1 to 1.75.0
  changelog/updates/2024-01-04-rust-1.75.0-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/files/1.75.0-119445.patch
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.75.0.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.75.0.ebuild
Labels: main

#1544 app-misc/jq: update to 1.7.1
  changelog/updates/2024-01-05-jq-1.7.1.md
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/portage-stable/app-misc/jq/Manifest
  sdk_container/src/third_party/portage-stable/app-misc/jq/jq-1.7.1.ebuild
Labels: main

#1551 Update net-misc/openssh
  changelog/security/2024-01-05-openssh-update.md
  changelog/updates/2024-01-05-openssh-update.md
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/Manifest
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/files/openssh-9.3_p1-GSSAPI-dns.patch
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/files/openssh-9.3_p1-openssl-ignore-status.patch
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/openssh-9.6_p1-r1.ebuild
Labels: main

#1552 Update dev-libs/openssl
  changelog/security/2024-01-05-openssl-update.md
  changelog/updates/2024-01-05-openssl-update.md
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/gentoo.config-1.0.4
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.9-CVE-2023-2975.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.9-CVE-2023-3446.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/metadata.xml
  sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/openssl-3.0.12.ebuild
Labels: main

#1564 overlay coreos-base/common-oem-files: Move gce to amd64-only OEMID list
  sdk_container/src/third_party/coreos-overlay/coreos-base/common-oem-files/common-oem-files-0-r5.ebuild
Labels: main

#1566 Changelog and accept keywords fixes
  changelog/security/2024-01-05-openssh-update.md
  changelog/security/2024-01-05-weekly-updates.md
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main

#1565 Upgrade Go from 1.20.12 to 1.20.13
  changelog/updates/2024-01-11-go-1.20.13-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.20.13.ebuild
Labels: main

#1571 coreos-cloudinit: fix hostname reset bug
  changelog/bugfixes/2024-01-15-coreos-cloudinit.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-cloudinit/coreos-cloudinit-1.14.0-r7.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
Labels: alpha, beta

#1572 app-emulation/amazon-ssm-agent: use upstream makefile
  changelog/bugfixes/2024-01-15-aws-ssm-agent.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/amazon-ssm-agent/amazon-ssm-agent-3.2.985.0-r2.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/amazon-ssm-agent/amazon-ssm-agent-3.2.985.0-r3.ebuild
Labels: alpha, beta

#1573 Upgrade Linux Kernel for main from 6.6.8 to 6.6.12
  changelog/updates/2024-01-16-linux-6.6.12-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.12.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.12.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.12.ebuild
Labels: main

#1574 Upgrade Linux Kernel for flatcar-3760 from 6.1.69 to 6.1.73
  changelog/updates/2024-01-16-linux-6.1.73-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.73.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.73.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.73.ebuild
Labels: beta

#1575 Upgrade Linux Kernel for flatcar-3510 from 5.15.144 to 5.15.147
  changelog/updates/2024-01-16-linux-5.15.147-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.147.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.147.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.147.ebuild
Labels: lts

#1576 Upgrade Linux Kernel for flatcar-3033 from 5.10.205 to 5.10.208
  changelog/updates/2024-01-16-linux-5.10.208-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.208.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.208.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.208.ebuild
Labels: lts

#1577 Upgrade Linux Kernel for flatcar-3602 from 5.15.144 to 5.15.147
  changelog/updates/2024-01-16-linux-5.15.147-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.147.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.147.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.147.ebuild
Labels: stable

#1578 Upgrade Linux Kernel for flatcar-3815 from 6.1.69 to 6.1.73
  changelog/updates/2024-01-16-linux-6.1.73-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.73.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.73.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.73.ebuild
Labels: alpha

#1581 overlay coreos-base/afterburn: update to 5.5.1
  changelog/updates/2024-01-17-afterburn-5.5.1-update.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/afterburn-5.5.1.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/afterburn-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/files/0003-cargo-reduce-binary-size-for-release-profile.patch
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/files/0003-vmware-arm64-unsupported.patch
Labels: main

#1580 coreos-base/(ue-rs|update_engine): Control extracted OEM payload name
  changelog/bugfixes/2024-01-16-self-hosted-oem-update-payloads.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-0.1.0-r6.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-0.4.10-r21.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-9999.ebuild
Labels: main

#1582 Upgrade Linux Firmware in main from 20231211 to 20240115
  changelog/updates/2024-01-18-linux-firmware-20240115-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20240115.ebuild
Labels: main

#1591 Upgrade Containerd in main from 1.7.11 to 1.7.12
  changelog/updates/2024-01-19-containerd-1.7.12-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.12.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main

#1610 Update ca-certificates in main from 3.96 to 3.97
  changelog/updates/2024-01-29-ca-certificates-3.97-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.97.ebuild
Labels: main

#1611 Update ca-certificates in flatcar-3033 from 3.96 to 3.97
  changelog/updates/2024-01-29-ca-certificates-3.97-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.97.ebuild
Labels: lts

#1612 Update ca-certificates in flatcar-3510 from 3.96 to 3.97
  changelog/updates/2024-01-29-ca-certificates-3.97-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.97.ebuild
Labels: lts

#1613 Update ca-certificates in flatcar-3760 from 3.96 to 3.97
  changelog/updates/2024-01-29-ca-certificates-3.97-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.97.ebuild
Labels: stable

#1614 Update ca-certificates in flatcar-3850 from 3.96 to 3.97
  changelog/updates/2024-01-29-ca-certificates-3.97-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.97.ebuild
Labels: alpha

#1615 Update ca-certificates in flatcar-3815 from 3.96 to 3.97
  changelog/updates/2024-01-29-ca-certificates-3.97-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.97.ebuild
Labels: beta

#1600 Backport XML passing to LTS as jump version for airgapped environments
  changelog/changes/2024-01-25-support-oem-payloads.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-0.4.10-r11.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-9999.ebuild
Labels: lts, flatcar-3510
