Repository flatcar/scripts, pull requests merged in 2024-02, with the labels that each got.

#1601 coreos-base/coreos-init: Add flatcar-update flag to skip OEM payloads
  changelog/changes/2024-01-25-flatcar-update-oem.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: main

#1622 Upgrade Containerd in main from 1.7.12 to 1.7.13
  changelog/updates/2024-02-02-containerd-1.7.13-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.13.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main

#1627 Upgrade Linux Kernel for main from 6.6.12 to 6.6.16
  changelog/updates/2024-02-06-linux-6.6.16-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.16.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.16.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.16.ebuild
Labels: main

#1607 Upgrade Linux Kernel for flatcar-3033 from 5.10.208 to 5.10.209
  changelog/updates/2024-01-26-linux-5.10.209-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.209.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.209.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.209.ebuild
Labels: lts

#1624 Upgrade Linux Kernel for flatcar-3760 from 6.1.73 to 6.1.77
  changelog/updates/2024-02-06-linux-6.1.77-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.77.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.77.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.77.ebuild
Labels: stable

#1625 Upgrade Linux Kernel for flatcar-3850 from 6.6.12 to 6.6.16
  changelog/updates/2024-02-06-linux-6.6.16-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.16.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.16.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.16.ebuild
Labels: alpha

#1626 Upgrade Linux Kernel for flatcar-3815 from 6.1.73 to 6.1.77
  changelog/updates/2024-02-06-linux-6.1.77-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.77.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.77.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.77.ebuild
Labels: beta

#1629 docker 24.0.9, runc 1.1.12, containerd 1.7.13 for alpha
  changelog/security/2024-02-06-docker.md
  changelog/updates/2024-02-06-docker.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.13.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/docker-cli-24.0.9.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/docker-cli-25.0.1.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker/docker-24.0.9.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker/docker-25.0.1.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/runc/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/runc/runc-1.1.12.ebuild
Labels: alpha

#1628 docker 24.0.9, runc 1.1.12, containerd 1.7.13 for beta
  changelog/security/2024-02-06-docker.md
  changelog/updates/2024-02-06-docker.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.13.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/docker-cli-24.0.7.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/docker-cli-24.0.9.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/docker-cli-25.0.1.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/metadata.xml
  sdk_container/src/third_party/portage-stable/app-containers/docker/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker/docker-24.0.7.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker/docker-24.0.9.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker/docker-25.0.1.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker/metadata.xml
  sdk_container/src/third_party/portage-stable/app-containers/runc/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/runc/runc-1.1.12.ebuild
Labels: beta

#1630 docker 24.0.9, runc 1.1.12 for main
  changelog/security/2024-02-06-docker.md
  changelog/updates/2024-02-06-docker.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.13.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-cli/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-cli/README.md
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-cli/docker-cli-24.0.9.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/docker-cli/metadata.xml
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/README.md
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/docker-24.0.9.ebuild
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/files/0001-Openrc-Depend-on-containerd-init-script.patch
  sdk_container/src/third_party/coreos-overlay/app-containers/docker/metadata.xml
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/docker-cli-25.0.1.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker/docker-25.0.1.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/runc/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/runc/runc-1.1.12.ebuild
Labels: main

#1647 Fix publishing of dev binpkgs
  build_dev_binpkgs
  sdk_container/src/third_party/portage-stable/dev-util/glib-utils/glib-utils-2.74.4.ebuild
Labels: lts

#1567 Update sys-libs/glibc to 2.38
  changelog/security/2024-02-08-glibc-update.md
  changelog/updates/2024-02-08-glibc-update.md
  sdk_container/src/third_party/coreos-overlay/sys-libs/glibc/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-libs/glibc/glibc-2.38-r10.ebuild
Labels: main

#1651 Upgrade Go from 1.20.13 to 1.20.14
  changelog/updates/2024-02-12-go-1.20.14-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.20.14.ebuild
Labels: main

#1653 Upgrade dev-lang/rust and virtual/rust in main from 1.75.0 to 1.76.0
  changelog/updates/2024-02-13-rust-1.76.0-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.76.0.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.76.0.ebuild
Labels: main

#1662 app-admin/sudo: update to 1.9.15_p5
  changelog/security/2024-02-13-sudo-1.9.15p5.md
  changelog/updates/2024-02-13-sudo-1.9.15p5.md
  sdk_container/src/third_party/coreos-overlay/app-admin/sudo/Manifest
  sdk_container/src/third_party/coreos-overlay/app-admin/sudo/sudo-1.9.15_p5.ebuild
Labels: main

#1638 .github: Some action version bumps to avoid deprecation warnings
  .github/workflows/cacerts-release.yaml
  .github/workflows/ci.yaml
  .github/workflows/containerd-release-main.yaml
  .github/workflows/firmware-release-main.yaml
  .github/workflows/go-release-main.yaml
  .github/workflows/kernel-release.yaml
  .github/workflows/mantle-releases-main.yml
  .github/workflows/run-kola-tests.yaml
  .github/workflows/rust-release-main.yaml
  .github/workflows/update-metadata-glsa.yaml
  .github/workflows/update-portage-stable-packages-from-list.yaml
  .github/workflows/update-sdk.yaml
  .github/workflows/vmware-release-main.yaml
Labels: github-actions

#1621 Monthly GLSA metadata 2024-02-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-07.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-08.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-09.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-10.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-11.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-12.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-13.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-14.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-15.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-16.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-17.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-18.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-19.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-20.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-21.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-22.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-23.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-24.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-25.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-26.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-27.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-28.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-29.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-30.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-31.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-32.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-33.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202401-34.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#1677 Update ca-certificates in main from 3.97 to 3.98
  changelog/updates/2024-02-19-ca-certificates-3.98-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.98.ebuild
Labels: main

#1673 Update ca-certificates in flatcar-3815 from 3.97 to 3.98
  changelog/updates/2024-02-19-ca-certificates-3.98-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.98.ebuild
Labels: stable

#1674 Update ca-certificates in flatcar-3033 from 3.97 to 3.98
  changelog/updates/2024-02-19-ca-certificates-3.98-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.98.ebuild
Labels: lts

#1675 Update ca-certificates in flatcar-3850 from 3.97 to 3.98
  changelog/updates/2024-02-19-ca-certificates-3.98-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.98.ebuild
Labels: beta

#1676 Update ca-certificates in flatcar-3874 from 3.97 to 3.98
  changelog/updates/2024-02-19-ca-certificates-3.98-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.98.ebuild
Labels: alpha

#1678 Update ca-certificates in flatcar-3510 from 3.97 to 3.98
  changelog/updates/2024-02-19-ca-certificates-3.98-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.98.ebuild
Labels: lts

#1681 app-crypt/gnupg: update to 2.2.42-r2
  .github/workflows/portage-stable-packages-list
  changelog/security/2024-02-20-gnupg-2.2.42.md
  changelog/updates/2024-02-20-gnupg-2.2.42.md
  sdk_container/src/third_party/coreos-overlay/app-crypt/gnupg/Manifest
  sdk_container/src/third_party/coreos-overlay/app-crypt/gnupg/files/gnupg-2.2.35-status-messages-garbled.patch
  sdk_container/src/third_party/coreos-overlay/app-crypt/gnupg/files/gnupg-accept-subkeys-with-a-good-revocation-but-no-self-sig.patch
  sdk_container/src/third_party/coreos-overlay/app-crypt/gnupg/files/gnupg-allow-import-of-previously-known-keys-even-without-UI.patch
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/Manifest
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/README-systemd
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/dirmngr.service
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/dirmngr.socket
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gnupg-2.1.20-gpgscm-Use-shorter-socket-path-lengts-to-improve-tes.patch
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gnupg-2.2.42-bug923248-insecure-backup.patch
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gnupg-2.4.2-fix-emacs.patch
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gnupg-2.4.3-no-ldap.patch
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gnupg-2.4.4-dirmngr-proxy.patch
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gpg-agent-browser.socket
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gpg-agent-extra.socket
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gpg-agent-ssh.socket
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gpg-agent.service
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/files/gpg-agent.socket
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/gnupg-2.2.41.ebuild
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/gnupg-2.2.42-r1.ebuild
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/gnupg-2.2.42-r2.ebuild
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/gnupg-2.4.3-r1.ebuild
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/gnupg-2.4.4-r1.ebuild
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/gnupg-2.4.4.ebuild
  sdk_container/src/third_party/portage-stable/app-crypt/gnupg/metadata.xml
Labels: main

#1686 Upgrade Linux Firmware in main from 20240115 to 20240220
  changelog/updates/2024-02-22-linux-firmware-20240220-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20240220.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
Labels: main

#1704 Drop app-containers/docker-proxy package
  .github/workflows/portage-stable-packages-list
  sdk_container/src/third_party/portage-stable/app-containers/docker-proxy/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker-proxy/docker-proxy-0.8.0_p20230118.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-proxy/metadata.xml
Labels: main

#1708 overlay coreos/config: Drop overrides for packages we do not have
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/app-admin/setools
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/app-emulation/xen
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/app-emulation/xen-tools
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-apps/busybox
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-apps/efunctions
Labels: main
