Repository flatcar/scripts, pull requests merged in 2024-10, with the labels that each got.

#2354 Monthly GLSA metadata 2024-10-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-07.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-08.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-09.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-10.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-11.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-12.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-13.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-14.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-15.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-16.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-17.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-18.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-19.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-20.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-21.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-22.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-23.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-24.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-25.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-26.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-27.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-28.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-29.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-30.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-31.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202409-32.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#2351 Upgrade Linux Kernel for main from 6.6.52 to 6.6.53
  changelog/updates/2024-10-01-linux-6.6.53-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.53.ebuild
Labels: main

#2350 Upgrade Linux Kernel for flatcar-4054 from 6.6.52 to 6.6.53
  changelog/updates/2024-10-01-linux-6.6.53-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.53.ebuild
Labels: beta

#2352 Upgrade Linux Kernel for flatcar-4081 from 6.6.52 to 6.6.53
  changelog/updates/2024-10-01-linux-6.6.53-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.53.ebuild
Labels: alpha

#2353 Upgrade Linux Kernel for flatcar-3975 from 6.6.52 to 6.6.53
  changelog/updates/2024-10-01-linux-6.6.53-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.53.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.53.ebuild
Labels: stable

#2246 overlay coreos-base/coreos-init: Pull in net fixes on diskless, blkid fix
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-0.0.1-r196.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: main

#2287 Switch to 23.0 profiles
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/amd64/parent
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/arm64/parent
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use.force
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/parent
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/use.force
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/use.mask
  sdk_container/src/third_party/coreos-overlay/profiles/features/systemd/make.defaults
  sdk_container/src/third_party/coreos-overlay/profiles/features/systemd/package.mask
  sdk_container/src/third_party/coreos-overlay/profiles/features/systemd/package.unmask
  sdk_container/src/third_party/coreos-overlay/profiles/features/systemd/package.use.force
  sdk_container/src/third_party/coreos-overlay/profiles/features/systemd/packages
  sdk_container/src/third_party/coreos-overlay/profiles/features/systemd/packages.build
  sdk_container/src/third_party/coreos-overlay/profiles/features/systemd/use.mask
  sdk_container/src/third_party/portage-stable/sys-apps/kmod/Manifest
  sdk_container/src/third_party/portage-stable/sys-apps/kmod/files/kmod-31-musl-basename.patch
  sdk_container/src/third_party/portage-stable/sys-apps/kmod/files/kmod-static-nodes-r1
  sdk_container/src/third_party/portage-stable/sys-apps/kmod/kmod-32-r2.ebuild
  sdk_container/src/third_party/portage-stable/sys-apps/kmod/kmod-33.ebuild
  sdk_container/src/third_party/portage-stable/sys-apps/kmod/kmod-9999.ebuild
  sdk_container/src/third_party/portage-stable/sys-apps/kmod/metadata.xml
Labels: main

#2317 upgrade Go, Runc, Docker and Containerd
  build_library/sysext_mangle_docker-flatcar
  changelog/security/2024-09-27-docker-go.md
  changelog/updates/2024-09-27-containerd-docker-go-runc.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.22.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/hard-host-depends/hard-host-depends-0.0.1-r212.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.22.7.ebuild
  sdk_container/src/third_party/coreos-overlay/eclass/coreos-go-depend.eclass
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker-cli/docker-cli-27.2.1.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker/docker-27.2.1.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/runc/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/runc/runc-1.1.14.ebuild
Labels: main

#2363 Upgrade Linux Kernel for main from 6.6.53 to 6.6.54
  changelog/updates/2024-10-05-linux-6.6.54-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.54.ebuild
Labels: main

#2360 Upgrade Linux Kernel for flatcar-4081 from 6.6.53 to 6.6.54
  changelog/updates/2024-10-05-linux-6.6.54-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.54.ebuild
Labels: alpha

#2361 Upgrade Linux Kernel for flatcar-4054 from 6.6.53 to 6.6.54
  changelog/updates/2024-10-05-linux-6.6.54-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.54.ebuild
Labels: beta

#2362 Upgrade Linux Kernel for flatcar-3975 from 6.6.53 to 6.6.54
  changelog/updates/2024-10-05-linux-6.6.54-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.54.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.54.ebuild
Labels: stable

#2365 Upgrade Go from 1.22.7 to 1.22.8
  changelog/updates/2024-10-07-go-1.22.8-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/go/go-1.22.8.ebuild
Labels: main

#2373 Add eclass/usr-ldscript.eclass to package automation
  .github/workflows/portage-stable-packages-list
  sdk_container/src/third_party/portage-stable/eclass/usr-ldscript.eclass
Labels: main

#2370 Upgrade Linux Kernel for main from 6.6.54 to 6.6.56
  changelog/updates/2024-10-11-linux-6.6.56-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.56.ebuild
Labels: main

#2369 Upgrade Linux Kernel for flatcar-4081 from 6.6.54 to 6.6.56
  changelog/updates/2024-10-11-linux-6.6.56-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.56.ebuild
Labels: beta

#2371 Upgrade Linux Kernel for flatcar-3975 from 6.6.54 to 6.6.56
  changelog/updates/2024-10-11-linux-6.6.56-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.56.ebuild
Labels: stable

#2372 Upgrade Linux Kernel for flatcar-4116 from 6.6.54 to 6.6.56
  changelog/updates/2024-10-11-linux-6.6.56-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.56.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.56.ebuild
Labels: alpha

#2380 Upgrade open-vm-tools in main from 12.4.5 to 12.5.0
  changelog/updates/2024-10-16-open-vm-tools-12.5.0-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/open-vm-tools/Manifest
  sdk_container/src/third_party/coreos-overlay/app-emulation/open-vm-tools/open-vm-tools-12.5.0.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-vmware/oem-vmware-12.5.0.ebuild
Labels: main

#2387 Upgrade Containerd in main from 1.7.22 to 1.7.23
  changelog/updates/2024-10-18-containerd-1.7.23-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.23.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main

#2390 sys-kernel/coreos-modules: disable CONFIG_NFS_V4_2_READ_PLUS
  changelog/updates/2024-10-22-disable-CONFIG_NFS_V4_2_READ_PLUS.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.6
Labels: alpha, beta, stable, main
