Repository flatcar/scripts, pull requests merged in 2024-08, with the labels that each got.

#2183 Monthly GLSA metadata 2024-08-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-09.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-10.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-11.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-12.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-13.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-14.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-15.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-16.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-17.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-18.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-19.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-20.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-21.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-22.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-23.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-24.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-25.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-26.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-27.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-28.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#2192 Add more eclasses to package automation
  .github/workflows/portage-stable-packages-list
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use
  sdk_container/src/third_party/portage-stable/eclass/check-reqs.eclass
  sdk_container/src/third_party/portage-stable/eclass/db-use.eclass
  sdk_container/src/third_party/portage-stable/eclass/gnome2-utils.eclass
  sdk_container/src/third_party/portage-stable/eclass/go-env.eclass
  sdk_container/src/third_party/portage-stable/eclass/go-module.eclass
  sdk_container/src/third_party/portage-stable/eclass/golang-base.eclass
  sdk_container/src/third_party/portage-stable/eclass/golang-vcs-snapshot.eclass
  sdk_container/src/third_party/portage-stable/eclass/golang-vcs.eclass
  sdk_container/src/third_party/portage-stable/eclass/linux-mod-r1.eclass
  sdk_container/src/third_party/portage-stable/eclass/llvm-r1.eclass
  sdk_container/src/third_party/portage-stable/eclass/mercurial.eclass
  sdk_container/src/third_party/portage-stable/eclass/mono-env.eclass
  sdk_container/src/third_party/portage-stable/eclass/perl-module.eclass
  sdk_container/src/third_party/portage-stable/eclass/qmake-utils.eclass
  sdk_container/src/third_party/portage-stable/eclass/secureboot.eclass
  sdk_container/src/third_party/portage-stable/eclass/sgml-catalog-r1.eclass
  sdk_container/src/third_party/portage-stable/eclass/ssl-cert.eclass
  sdk_container/src/third_party/portage-stable/eclass/subversion.eclass
  sdk_container/src/third_party/portage-stable/eclass/vcs-snapshot.eclass
  sdk_container/src/third_party/portage-stable/eclass/xdg.eclass
Labels: main

#2190 overlay coreos-base/ue-rs: update version to 20240801
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-0.1.0-r8.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-9999.ebuild
Labels: main

#2079 Replace nmap netcat with openbsd netcat
  .github/workflows/portage-stable-packages-list
  changelog/changes/2024-07-01-replace-nmap.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-0.0.1-r195.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos/coreos-0.0.1.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/net-analyzer/openbsd-netcat
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/make.defaults
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/generic/oem-aci/make.defaults
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/generic/package.provided
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/generic/prod/make.defaults
  sdk_container/src/third_party/portage-stable/dev-lang/lua/Manifest
  sdk_container/src/third_party/portage-stable/dev-lang/lua/files/5.1/0001-extern_C.patch
  sdk_container/src/third_party/portage-stable/dev-lang/lua/files/5.1/0002-Fix-stack-overflow-in-vararg-functions.patch
  sdk_container/src/third_party/portage-stable/dev-lang/lua/files/lua-5.1.4-test.patch
  sdk_container/src/third_party/portage-stable/dev-lang/lua/files/lua-5.4.6-sparc-tests.patch
  sdk_container/src/third_party/portage-stable/dev-lang/lua/lua-5.1.5-r200.ebuild
  sdk_container/src/third_party/portage-stable/dev-lang/lua/lua-5.3.6-r102.ebuild
  sdk_container/src/third_party/portage-stable/dev-lang/lua/lua-5.4.6.ebuild
  sdk_container/src/third_party/portage-stable/dev-lang/lua/metadata.xml
  sdk_container/src/third_party/portage-stable/net-analyzer/nmap/Manifest
  sdk_container/src/third_party/portage-stable/net-analyzer/nmap/files/nls.m4
  sdk_container/src/third_party/portage-stable/net-analyzer/nmap/files/nmap-7.94-autoconf-2.72.patch
  sdk_container/src/third_party/portage-stable/net-analyzer/nmap/files/nmap-7.94-topport.patch
  sdk_container/src/third_party/portage-stable/net-analyzer/nmap/metadata.xml
  sdk_container/src/third_party/portage-stable/net-analyzer/nmap/nmap-7.94-r1.ebuild
  sdk_container/src/third_party/portage-stable/net-analyzer/nmap/nmap-7.94.ebuild
  sdk_container/src/third_party/portage-stable/net-analyzer/nmap/nmap-7.95.ebuild
  sdk_container/src/third_party/portage-stable/net-analyzer/nmap/nmap-9999.ebuild
  sdk_container/src/third_party/portage-stable/net-analyzer/openbsd-netcat/Manifest
  sdk_container/src/third_party/portage-stable/net-analyzer/openbsd-netcat/files/openbsd-netcat-1.105-musl-b64_ntop.patch
  sdk_container/src/third_party/portage-stable/net-analyzer/openbsd-netcat/files/openbsd-netcat-1.190-darwin13.patch
  sdk_container/src/third_party/portage-stable/net-analyzer/openbsd-netcat/files/openbsd-netcat-1.219-darwin.patch
  sdk_container/src/third_party/portage-stable/net-analyzer/openbsd-netcat/metadata.xml
  sdk_container/src/third_party/portage-stable/net-analyzer/openbsd-netcat/openbsd-netcat-1.218_p5.ebuild
  sdk_container/src/third_party/portage-stable/net-analyzer/openbsd-netcat/openbsd-netcat-1.219_p1.ebuild
Labels: main

#2233 Upgrade Linux Firmware in main from 20240709 to 20240811
  changelog/security/2024-08-19-linux-firmware-20240811.md
  changelog/updates/2024-08-15-linux-firmware-20240811-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20240811.ebuild
Labels: main

#2222 coreos-cloudinit: fix Equinix Metal cloudinit
  changelog/bugfixes/2024-08-21-cloudinit-equinix.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-cloudinit/coreos-cloudinit-1.14.0-r9.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
Labels: main

#2260 config/env/sys-fs/zfs-kmod: un-break zfs-kmod binpkg install
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-fs/zfs-kmod
Labels: main

#2267 Upgrade Containerd in main from 1.7.20 to 1.7.21
  changelog/updates/2024-08-30-containerd-1.7.21-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.21.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main

#2262 Upgrade Linux Kernel for main from 6.6.47 to 6.6.48
  changelog/updates/2024-08-30-linux-6.6.48-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.48.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.48.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.48.ebuild
Labels: main

#2263 Upgrade Linux Kernel for flatcar-4054 from 6.6.47 to 6.6.48
  changelog/updates/2024-08-30-linux-6.6.48-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.48.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.48.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.48.ebuild
Labels: alpha

#2264 Upgrade Linux Kernel for flatcar-4012 from 6.6.47 to 6.6.48
  changelog/updates/2024-08-30-linux-6.6.48-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.48.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.48.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.48.ebuild
Labels: beta

#2236 Add image changes reports for extra sysexts
  ci-automation/image_changes.sh
Labels: main
