Repository flatcar/scripts, pull requests merged in 2024-05, with the labels that each got.

#1969 Upgrade Linux Kernel for flatcar-3510 from 5.15.156 to 5.15.158
  changelog/updates/2024-05-03-linux-5.15.158-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.158.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.158.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.158.ebuild
Labels: lts

#1987 Update ca-certificates in main from 3.99 to 3.100
  changelog/updates/2024-05-13-ca-certificates-3.100-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.100.ebuild
Labels: main

#1983 Update ca-certificates in flatcar-3913 from 3.99 to 3.100
  changelog/updates/2024-05-13-ca-certificates-3.100-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.100.ebuild
Labels: beta

#1984 Update ca-certificates in flatcar-3510 from 3.99 to 3.100
  changelog/updates/2024-05-13-ca-certificates-3.100-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.100.ebuild
Labels: lts

#1985 Update ca-certificates in flatcar-3941 from 3.99 to 3.100
  changelog/updates/2024-05-13-ca-certificates-3.100-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.100.ebuild
Labels: alpha

#1986 Update ca-certificates in flatcar-3815 from 3.99 to 3.100
  changelog/updates/2024-05-13-ca-certificates-3.100-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.100.ebuild
Labels: stable

#1989 Upgrade Linux Firmware in main from 20240410 to 20240513
  changelog/updates/2024-05-16-linux-firmware-20240513-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20240513.ebuild
Labels: main

#1991 Upgrade Containerd in main from 1.7.16 to 1.7.17
  changelog/updates/2024-05-17-containerd-1.7.17-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.17.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main

#1990 sys-libs/glibc: update to 2.38-r13
  changelog/security/2024-05-16-glibc-2.38-r13.md
  sdk_container/src/third_party/coreos-overlay/sys-libs/glibc/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-libs/glibc/glibc-2.38-r13.ebuild
Labels: alpha, beta, main

#1970 Upgrade Linux Kernel for main from 6.6.28 to 6.6.30
  changelog/updates/2024-05-03-linux-6.6.30-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0002-revert-pahole-flags.patch
Labels: main

#1968 Upgrade Linux Kernel for flatcar-3941 from 6.6.28 to 6.6.30
  changelog/updates/2024-05-03-linux-6.6.30-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0002-revert-pahole-flags.patch
Labels: alpha

#1972 Upgrade Linux Kernel for flatcar-3913 from 6.6.28 to 6.6.30
  changelog/updates/2024-05-03-linux-6.6.30-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.30.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0002-revert-pahole-flags.patch
Labels: beta

#1971 Upgrade Linux Kernel for flatcar-3815 from 6.1.87 to 6.1.90
  changelog/updates/2024-05-03-linux-6.1.90-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.90.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.90.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.90.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.1/z0002-revert-pahole-flags.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.1/z0003-Revert-x86-boot-Remove-the-bugger-off-message.patch
Labels: stable

#1981 Upgrade dev-lang/rust and virtual/rust in main from 1.77.2 to 1.78.0
  changelog/updates/2024-05-07-rust-1.78.0-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/files/1.78.0-ignore-broken-and-non-applicable-tests.patch
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.78.0.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.78.0.ebuild
Labels: main

#1732 Migrate from glibc libcrypt to sys-libs/libxcrypt
  .github/workflows/portage-stable-packages-list
  bootstrap_sdk
  changelog/changes/2024-03-08-libcrypt-migration.md
  sdk_container/src/third_party/coreos-overlay/coreos/stage1_hooks/0000-glibc-crypt-portage-stable.sh
  sdk_container/src/third_party/coreos-overlay/coreos/stage1_hooks/0002-glibc-crypt-coreos-overlay.sh
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.mask
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use.force
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use.mask
  sdk_container/src/third_party/portage-stable/sys-libs/libxcrypt/Manifest
  sdk_container/src/third_party/portage-stable/sys-libs/libxcrypt/files/libxcrypt-4.4.19-multibuild.patch
  sdk_container/src/third_party/portage-stable/sys-libs/libxcrypt/libxcrypt-4.4.36-r2.ebuild
  sdk_container/src/third_party/portage-stable/sys-libs/libxcrypt/libxcrypt-4.4.36-r3.ebuild
  sdk_container/src/third_party/portage-stable/sys-libs/libxcrypt/libxcrypt-4.4.36.ebuild
  sdk_container/src/third_party/portage-stable/sys-libs/libxcrypt/metadata.xml
Labels: main
