Repository flatcar/scripts, pull requests merged in 2024-04, with the labels that each got.

#1818 Upgrade dev-lang/rust and virtual/rust in main from 1.77.0 to 1.77.1
  changelog/updates/2024-04-02-rust-1.77.1-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.77.1.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.77.1.ebuild
Labels: main

#1855 net-fs/samba: update to 4.18.9
  changelog/updates/2024-04-08-samba-4.18.9.md
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/Manifest
  sdk_container/src/third_party/coreos-overlay/net-fs/samba/samba-4.18.9.ebuild
Labels: main

#1886 Upgrade Containerd in main from 1.7.14 to 1.7.15
  changelog/updates/2024-04-12-containerd-1.7.15-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.15.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main

#1888 coreos-base/ue-rs: bump h2, mio
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-0.1.0-r7.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-9999.ebuild
Labels: main

#1872 Upgrade Linux Kernel for flatcar-3510 from 5.15.153 to 5.15.154
  changelog/updates/2024-04-11-linux-5.15.154-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.154.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.154.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.154.ebuild
Labels: lts

#1907 Upgrade dev-lang/rust and virtual/rust in main from 1.77.1 to 1.77.2
  changelog/updates/2024-04-16-rust-1.77.2-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.77.2.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.77.2.ebuild
Labels: main

#1948 Add CONFIG_PPS_CLIENT_GPIO=m
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/arm64_defconfig-6.6
Labels: main

#1753 overlay sys-apps/systemd: Sync with Gentoo, bump to v255.4 and add patches for mutable overlays functionality
  changelog/changes/2024-04-22-systemd-sysext.md
  changelog/updates/2024-04-22-systemd-sysext.md
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0001-wait-online-set-any-by-default.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0002-networkd-default-to-kernel-IPForwarding-setting.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0003-needs-update-don-t-require-strictly-newer-usr.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0004-core-use-max-for-DefaultTasksMax.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0005-systemd-Disable-SELinux-permissions-checks.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0006-Revert-getty-Pass-tty-to-use-by-agetty-via-stdin.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0007-units-Keep-using-old-journal-file-format.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0008-Revert-core-service-when-resetting-PID-also-reset-known.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0008-sysext-Mutable-overlays.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/254-PrivateDevices-userdbd.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/255-install-format-overflow.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/systemd-253-initrd-generators.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/systemd-255.4.ebuild
Labels: main

#1931 Upgrade Linux Kernel for main from 6.6.21 to 6.6.28
  changelog/updates/2024-04-18-linux-6.6.28-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.28.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.28.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.28.ebuild
Labels: main

#1932 Upgrade Linux Kernel for flatcar-3913 from 6.6.21 to 6.6.28
  changelog/updates/2024-04-18-linux-6.6.28-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.28.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.28.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.28.ebuild
Labels: beta

#1935 Upgrade Linux Kernel for flatcar-3941 from 6.6.21 to 6.6.28
  changelog/updates/2024-04-18-linux-6.6.28-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.28.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.28.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.28.ebuild
Labels: alpha

#1917 Upgrade Linux Kernel for flatcar-3033 from 5.10.214 to 5.10.215
  changelog/updates/2024-04-17-linux-5.10.215-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.215.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.215.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.215.ebuild
Labels: lts

#1934 Upgrade Linux Kernel for flatcar-3510 from 5.15.154 to 5.15.156
  changelog/updates/2024-04-18-linux-5.15.156-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.156.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.156.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.156.ebuild
Labels: lts

#1956 Upgrade Containerd in main from 1.7.15 to 1.7.16
  changelog/updates/2024-04-26-containerd-1.7.16-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.16.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main
