Repository flatcar/scripts, pull requests merged in 2024-09, with the labels that each got.

#2266 fix ownership of containerd/docker sysext files
  build_library/sysext_mangle_containerd-flatcar
  build_library/sysext_mangle_docker-flatcar
  build_sysext
  changelog/bugfixes/2024-08-30-fix-sysext-file-ownership.md
Labels: alpha, lts, beta, stable, main

#2268 Monthly GLSA metadata 2024-09-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-07.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-08.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-09.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-10.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-11.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-12.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-13.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-14.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-15.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-16.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-17.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-18.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-19.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-20.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-21.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-22.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-23.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-24.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-25.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-26.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-27.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-28.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-29.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-30.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-31.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-32.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202408-33.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#2261 sys-block/open-iscsi: Migrate coreos-stable to portage-stable, 2.1.10
  .github/workflows/portage-stable-packages-list
  changelog/updates/2024-08-26-open-iscsi-update.md
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-block/open-iscsi
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/sys-block/open-iscsi/README.md
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/sys-block/open-iscsi/open-iscsi-startup-automatic.patch
  sdk_container/src/third_party/coreos-overlay/sys-block/open-iscsi/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-block/open-iscsi/files/iscsi-init.service
  sdk_container/src/third_party/coreos-overlay/sys-block/open-iscsi/files/open-iscsi-2.1.1-Makefiles.patch
  sdk_container/src/third_party/coreos-overlay/sys-block/open-iscsi/files/open-iscsi.conf
  sdk_container/src/third_party/coreos-overlay/sys-block/open-iscsi/open-iscsi-2.1.4-r1.ebuild
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/Manifest
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/files/initiatorname.iscsi
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/files/iscsid-conf.d
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/files/iscsid-init.d
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/files/open-iscsi-2.1.7-fix_bitwise.patch
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/files/open-iscsi-2.1.9-usr-idbm.c-fix-musl-build-426.patch
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/metadata.xml
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/open-iscsi-2.1.10.ebuild
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/open-iscsi-2.1.8.ebuild
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/open-iscsi-2.1.9.ebuild
Labels: main

#2204 Add app-containers/docker-buildx
  .github/workflows/portage-stable-packages-list
  build_docker_aci
  build_image
  build_library/ebuild_aci_manifest.in
  build_library/ebuild_aci_util.sh
  changelog/changes/2024-08-05-buildx.md
  ci-automation/base_sysexts.sh
  sdk_container/src/third_party/coreos-overlay/coreos-devel/board-packages/board-packages-0.0.1-r15.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-devel/board-packages/board-packages-0.0.1.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/sec-policy/flatcar-selinux-patches/0001-Flatcar-modifications.patch
  sdk_container/src/third_party/portage-stable/app-containers/docker-buildx/Manifest
  sdk_container/src/third_party/portage-stable/app-containers/docker-buildx/docker-buildx-0.10.4-r1.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-buildx/docker-buildx-0.11.2.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-buildx/docker-buildx-0.14.0.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-buildx/docker-buildx-9999.ebuild
  sdk_container/src/third_party/portage-stable/app-containers/docker-buildx/metadata.xml
Labels: main

#2275 overlay coreos/user-patches: Add a symlink for selinux-policykit
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/sec-policy/selinux-policykit
Labels: main

#2068 Finish merged-usr process for generic images, move SDK over to it too
  changelog/changes/2024-09-05-sbin-merge.md
  sdk_container/src/third_party/coreos-overlay/app-admin/sudo/sudo-1.9.15_p5.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-0.4.10-r23.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-apps/kmod
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/make.defaults
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/use.force
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/use.mask
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/generic/make.defaults
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/generic/use.mask
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/sdk/make.defaults
  sdk_container/src/third_party/coreos-overlay/sys-apps/baselayout/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-apps/baselayout/baselayout-3.6.8-r16.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-apps/baselayout/baselayout-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.48.ebuild
Labels: main

#2309 oem-azure: add hyperv daemons
  .github/workflows/kernel-apply-patch.sh
  changelog/changes/2024-09-12-azure-hv-daemons.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/files/hv_fcopy_daemon.service
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/files/hv_kvp_daemon.service
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/files/hv_vss_daemon.service
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.50.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/metadata.xml
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-azure/oem-azure-2.9.1.1-r3.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-hyperv/oem-hyperv-0.1.0-r1.ebuild
Labels: alpha, beta, stable, main

#2321 .github: Handle missing app-emulation/hv-daemons
  .github/workflows/kernel-apply-patch.sh
Labels: alpha, lts, beta, stable, main

#2318 sys-boot/grub: Move to portage-stable, bump to 2.12
  .github/workflows/portage-stable-packages-list
  changelog/updates/2024-09-06-grub-2.12.md
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-boot/grub
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/sys-boot/grub/README.md
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/sys-boot/grub/grub-2.12-add-gpt-partition-scheme.patch
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/sys-boot/grub/grub-2.12-add-verity-hash.patch
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-boot/grub/files/sbat.csv.in
  sdk_container/src/third_party/portage-stable/sys-boot/grub/Manifest
  sdk_container/src/third_party/portage-stable/sys-boot/grub/files/gfxpayload.patch
  sdk_container/src/third_party/portage-stable/sys-boot/grub/files/grub-2.02_beta2-KERNEL_GLOBS.patch
  sdk_container/src/third_party/portage-stable/sys-boot/grub/files/grub-2.06-test-words.patch
  sdk_container/src/third_party/portage-stable/sys-boot/grub/files/grub-2.12-fwsetup.patch
  sdk_container/src/third_party/portage-stable/sys-boot/grub/files/grub.default-4
  sdk_container/src/third_party/portage-stable/sys-boot/grub/files/sbat.csv
  sdk_container/src/third_party/portage-stable/sys-boot/grub/grub-2.12-r4.ebuild
  sdk_container/src/third_party/portage-stable/sys-boot/grub/grub-2.12-r5.ebuild
  sdk_container/src/third_party/portage-stable/sys-boot/grub/grub-9999.ebuild
  sdk_container/src/third_party/portage-stable/sys-boot/grub/metadata.xml
Labels: main

#2299 secure boot: lockdown, grub fallback, CI
  .github/workflows/run-kola-tests.yaml
  build_library/grub.cfg
  changelog/changes/2024-09-10-kernel-lockdown.md
  ci-automation/ci-config.env
  ci-automation/vendor-testing/qemu.sh
  ci-automation/vendor-testing/qemu_update.sh
  run_local_tests.sh
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.6
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.51.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0004-efi-Add-an-EFI_SECURE_BOOT-flag-to-indicate-secure-b.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0005-efi-Lock-down-the-kernel-if-booted-in-secure-boot-mo.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0006-mtd-phram-slram-Disable-when-the-kernel-is-locked-do.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0007-arm64-add-kernel-config-option-to-lock-down-when-in-.patch
Labels: main

#2345 Update ca-certificates in main from 3.104 to 3.105
  changelog/updates/2024-09-30-ca-certificates-3.105-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.105.ebuild
Labels: main

#2344 Update ca-certificates in flatcar-4081 from 3.104 to 3.105
  changelog/updates/2024-09-30-ca-certificates-3.105-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.105.ebuild
Labels: alpha

#2346 Update ca-certificates in flatcar-4054 from 3.104 to 3.105
  changelog/updates/2024-09-30-ca-certificates-3.105-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.105.ebuild
Labels: beta

#2347 Update ca-certificates in flatcar-3975 from 3.104 to 3.105
  changelog/updates/2024-09-30-ca-certificates-3.105-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.105.ebuild
Labels: stable

#2348 Update ca-certificates in flatcar-3510 from 3.104 to 3.105
  changelog/updates/2024-09-30-ca-certificates-3.105-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.105.ebuild
Labels: lts
