Repository flatcar/scripts, pull requests merged in 2024-03, with the labels that each got.

#1669 Upgrade Linux Kernel for main from 6.6.16 to 6.6.17
  changelog/updates/2024-02-17-linux-6.6.17-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.17.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.17.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.17.ebuild
Labels: main

#1668 Upgrade Linux Kernel for flatcar-3850 from 6.6.16 to 6.6.17
  changelog/updates/2024-02-17-linux-6.6.17-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.17.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.17.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.17.ebuild
Labels: beta

#1671 Upgrade Linux Kernel for flatcar-3874 from 6.6.16 to 6.6.17
  changelog/updates/2024-02-17-linux-6.6.17-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.17.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.17.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.17.ebuild
Labels: alpha

#1718 Upgrade Linux Kernel for flatcar-3815 from 6.1.77 to 6.1.80
  changelog/updates/2024-03-02-linux-6.1.80-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.80.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.80.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.1
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.80.ebuild
Labels: stable

#1720 Upgrade Linux Kernel for flatcar-3033 from 5.10.209 to 5.10.211
  changelog/updates/2024-03-02-linux-5.10.211-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.211.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.211.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-5.10
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.211.ebuild
Labels: lts

#1721 Upgrade Linux Kernel for flatcar-3510 from 5.15.148 to 5.15.150
  changelog/updates/2024-03-02-linux-5.15.150-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.150.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.150.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-5.15
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.150.ebuild
Labels: lts

#1733 Drop unused net-libs/libssh2 package
  .github/workflows/portage-stable-packages-list
  sdk_container/src/third_party/portage-stable/net-libs/libssh2/Manifest
  sdk_container/src/third_party/portage-stable/net-libs/libssh2/files/libssh2-1.11.0-mansyntax_sh.patch
  sdk_container/src/third_party/portage-stable/net-libs/libssh2/files/libssh2-1.11.0-size_t.patch
  sdk_container/src/third_party/portage-stable/net-libs/libssh2/libssh2-1.11.0-r2.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libssh2/libssh2-9999.ebuild
  sdk_container/src/third_party/portage-stable/net-libs/libssh2/metadata.xml
Labels: main

#1679 sys-apps/systemd: upgrade from version 252 to version 255
  changelog/updates/2024-03-13-systemd-upgrade-from-252-to-255.md
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/packages
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/CHECKLIST.md
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0004-core-use-max-for-DefaultTasksMax.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/0007-units-Keep-using-old-journal-file-format.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/252-no-stack-protector-bpf.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/254-PrivateDevices-userdbd.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/gentoo-journald-audit-r1.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/gentoo-journald-audit.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/gentoo-systemctl-disable-sysv-sync-r1.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/legacy.conf
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/systemd-253-initrd-generators.patch
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/files/systemd-flatcar.conf
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/metadata.xml
  sdk_container/src/third_party/coreos-overlay/sys-apps/systemd/systemd-255.3.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-fs/udev-init-scripts/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-fs/udev-init-scripts/metadata.xml
  sdk_container/src/third_party/coreos-overlay/sys-fs/udev-init-scripts/udev-init-scripts-35.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-fs/udev-init-scripts/udev-init-scripts-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/dracut/dracut-053-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/dracut/files/0001-systemd-initrd-install-only-keymap-required-by-syste.patch
  sdk_container/src/third_party/portage-stable/profiles/features/prefix/packages
Labels: main

#1740 Upgrade Linux Kernel for flatcar-3815 from 6.1.80 to 6.1.81
  changelog/updates/2024-03-07-linux-6.1.81-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.1.81.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.1.81.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.1.81.ebuild
Labels: stable

#1739 Upgrade Linux Kernel for flatcar-3033 from 5.10.211 to 5.10.212
  changelog/updates/2024-03-07-linux-5.10.212-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.10.212.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.10.212.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.10.212.ebuild
Labels: lts

#1738 Upgrade Linux Kernel for flatcar-3510 from 5.15.150 to 5.15.151
  changelog/updates/2024-03-07-linux-5.15.151-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.151.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.151.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.151.ebuild
Labels: lts

#1736 Upgrade Linux Kernel for main from 6.6.17 to 6.6.21
  changelog/updates/2024-03-07-linux-6.6.21-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0003-Revert-x86-boot-Remove-the-bugger-off-message.patch
Labels: main, on-hold

#1737 Upgrade Linux Kernel for flatcar-3850 from 6.6.17 to 6.6.21
  changelog/updates/2024-03-07-linux-6.6.21-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0003-Revert-x86-boot-Remove-the-bugger-off-message.patch
Labels: beta, on-hold

#1735 Upgrade Linux Kernel for flatcar-3874 from 6.6.17 to 6.6.21
  changelog/updates/2024-03-07-linux-6.6.21-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.21.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0003-Revert-x86-boot-Remove-the-bugger-off-message.patch
Labels: alpha, on-hold

#1744 Upgrade Linux Firmware in main from 20240220 to 20240312
  changelog/updates/2024-03-14-linux-firmware-20240312-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20240312.ebuild
Labels: main

#1752 Upgrade Containerd in main from 1.7.13 to 1.7.14
  changelog/updates/2024-03-15-containerd-1.7.14-update.md
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/Manifest
  sdk_container/src/third_party/coreos-overlay/app-containers/containerd/containerd-1.7.14.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
Labels: main

#1768 Update ca-certificates in main from 3.98 to 3.99
  changelog/updates/2024-03-18-ca-certificates-3.99-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.99.ebuild
Labels: main

#1764 Update ca-certificates in flatcar-3510 from 3.98 to 3.99
  changelog/updates/2024-03-18-ca-certificates-3.99-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.99.ebuild
Labels: lts

#1766 Update ca-certificates in flatcar-3033 from 3.98 to 3.99
  changelog/updates/2024-03-18-ca-certificates-3.99-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.99.ebuild
Labels: lts

#1767 Update ca-certificates in flatcar-3850 from 3.98 to 3.99
  changelog/updates/2024-03-18-ca-certificates-3.99-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.99.ebuild
Labels: beta

#1769 Update ca-certificates in flatcar-3874 from 3.98 to 3.99
  changelog/updates/2024-03-18-ca-certificates-3.99-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.99.ebuild
Labels: alpha

#1781 Backport openssh-9.6p1 to stable
  changelog/security/2024-01-05-openssh-update.md
  changelog/updates/2024-01-05-openssh-update.md
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/Manifest
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/files/openssh-9.3_p1-GSSAPI-dns.patch
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/files/openssh-9.3_p1-openssl-ignore-status.patch
  sdk_container/src/third_party/coreos-overlay/net-misc/openssh/openssh-9.6_p1-r1.ebuild
Labels: stable

#1789 Update ca-certificates in flatcar-3913 from 3.98 to 3.99
  changelog/updates/2024-03-25-ca-certificates-3.99-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.99.ebuild
Labels: alpha

#1793 Upgrade dev-lang/rust and virtual/rust in main from 1.76.0 to 1.77.0
  changelog/updates/2024-03-26-rust-1.77.0-update.md
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/files/1.77.0-119445.patch
  sdk_container/src/third_party/coreos-overlay/dev-lang/rust/rust-1.77.0.ebuild
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.unmask
  sdk_container/src/third_party/coreos-overlay/virtual/rust/rust-1.77.0.ebuild
Labels: main

#1797 Upgrade open-vm-tools in main from 12.3.5 to 12.4.0
  changelog/updates/2024-03-27-open-vm-tools-12.4.0-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/open-vm-tools/Manifest
  sdk_container/src/third_party/coreos-overlay/app-emulation/open-vm-tools/open-vm-tools-12.4.0.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-vmware/oem-vmware-12.4.0.ebuild
Labels: main

#1805 Cleanups
  .github/workflows/portage-stable-packages-list
  sdk_container/src/third_party/coreos-overlay/dev-libs/jose/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-libs/jose/jose-11-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/dev-libs/jose/jose-12.ebuild
  sdk_container/src/third_party/coreos-overlay/dev-libs/jose/metadata.xml
  sdk_container/src/third_party/coreos-overlay/dev-libs/luksmeta/Manifest
  sdk_container/src/third_party/coreos-overlay/dev-libs/luksmeta/files/luksmeta-tests.patch
  sdk_container/src/third_party/coreos-overlay/dev-libs/luksmeta/luksmeta-9-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/dev-libs/luksmeta/metadata.xml
  sdk_container/src/third_party/portage-stable/sys-apps/keyutils/Manifest
  sdk_container/src/third_party/portage-stable/sys-apps/keyutils/files/keyutils-1.5.10-disable-tests.patch
  sdk_container/src/third_party/portage-stable/sys-apps/keyutils/files/keyutils-1.5.9-header-extern-c.patch
  sdk_container/src/third_party/portage-stable/sys-apps/keyutils/files/keyutils-1.6-makefile-fixup.patch
  sdk_container/src/third_party/portage-stable/sys-apps/keyutils/files/keyutils-1.6.3-fix-rpmspec-check.patch
  sdk_container/src/third_party/portage-stable/sys-apps/keyutils/files/keyutils-1.6.3-tests.patch
  sdk_container/src/third_party/portage-stable/sys-apps/keyutils/keyutils-1.6.3-r1.ebuild
  sdk_container/src/third_party/portage-stable/sys-apps/keyutils/metadata.xml
  sdk_container/src/third_party/portage-stable/sys-auth/Manifest
  sdk_container/src/third_party/portage-stable/sys-auth/files/polkit-122-libs-only-postinstall.patch
  sdk_container/src/third_party/portage-stable/sys-auth/files/polkit-123-mozjs-JIT.patch
  sdk_container/src/third_party/portage-stable/sys-auth/files/polkit-123-pkexec-uninitialized.patch
  sdk_container/src/third_party/portage-stable/sys-auth/files/polkit-124-systemd-fixup.patch
  sdk_container/src/third_party/portage-stable/sys-auth/files/polkit-124-systemd.patch
  sdk_container/src/third_party/portage-stable/sys-auth/metadata.xml
  sdk_container/src/third_party/portage-stable/sys-auth/polkit-122-r1.ebuild
  sdk_container/src/third_party/portage-stable/sys-auth/polkit-123.ebuild
  sdk_container/src/third_party/portage-stable/sys-auth/polkit-124-r1.ebuild
Labels: main
