Repository flatcar/scripts, pull requests merged in 2024-07, with the labels that each got.

#2063 Pull in latest mantle, drop obsolete auth flags
  ci-automation/garbage_collect_cloud.sh
  ci-automation/release.sh
  ci-automation/vendor-testing/azure.sh
  sdk_container/.repo/manifests/mantle-container
Labels: main

#2081 Pull in latest mantle, drop obsolete auth flags
  ci-automation/garbage_collect_cloud.sh
  ci-automation/release.sh
  ci-automation/vendor-testing/azure.sh
  sdk_container/.repo/manifests/mantle-container
Labels: beta

#2082 Pull in latest mantle, drop obsolete auth flags
  ci-automation/garbage_collect_cloud.sh
  ci-automation/release.sh
  ci-automation/vendor-testing/azure.sh
  sdk_container/.repo/manifests/mantle-container
Labels: alpha

#2083 Pull in latest mantle, drop obsolete auth flags
  ci-automation/garbage_collect_cloud.sh
  ci-automation/release.sh
  ci-automation/vendor-testing/azure.sh
  sdk_container/.repo/manifests/mantle-container
Labels: stable

#2114 Upgrade Linux Firmware in main from 20240610 to 20240709
  changelog/updates/2024-07-11-linux-firmware-20240709-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20240709.ebuild
Labels: main

#2069 Monthly GLSA metadata 2024-07-01
  build_library/test_image_content.sh
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202403-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-07.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-08.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-09.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-10.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-11.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-12.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-13.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-14.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-15.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-16.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-17.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-18.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-19.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-20.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-21.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-22.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-23.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-24.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-25.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-26.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-27.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-28.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-29.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-30.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-31.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-32.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202405-33.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202406-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202406-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202406-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202406-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202406-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202406-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-07.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202407-08.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#2158 Enable Landlock
  changelog/changes/2024-07-29-landlock.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.6
Labels: main
