Repository flatcar/scripts, pull requests merged in 2025-03, with the labels that each got.

#2697 overlay wa-linux-agent: apply patch to fix ssh public key override issue (main)
  changelog/bugfixes/2025-02-28-walinuxagent-ignition.md
  changelog/updates/2025-02-28-walinuxagent-2.12.0.4.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/wa-linux-agent/Manifest
  sdk_container/src/third_party/coreos-overlay/app-emulation/wa-linux-agent/files/0001-flatcar-changes.patch
  sdk_container/src/third_party/coreos-overlay/app-emulation/wa-linux-agent/files/0002-prevent-ssh-public-key-override.patch
  sdk_container/src/third_party/coreos-overlay/app-emulation/wa-linux-agent/wa-linux-agent-2.12.0.4-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/oem-azure/oem-azure-2.12.0.4-r1.ebuild
Labels: main

#2706 Monthly GLSA metadata 2025-03-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202305-30.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202502-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#2615 Improve package updates reporting and add more build deps to SDK
  sdk_container/src/third_party/coreos-overlay/coreos-base/hard-host-depends/hard-host-depends-0.0.1-r213.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-devel/sdk-depends/sdk-depends-0.0.1-r55.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild
Labels: main

#2720 Add README badges with socials and the main website
  README.md
Labels: main

#2738 overlay coreos-init: Distribute new sub key 2025
  changelog/changes/2025-03-10-image-signing-key.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-0.0.1-r198.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: alpha, lts, beta, stable, main

#2740 Upgrade Linux Firmware in main from 20250211 to 20250311
  changelog/updates/2025-03-13-linux-firmware-20250311-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20250311.ebuild
Labels: main

#2749 Update ca-certificates in flatcar-3510 from 3.107 to 3.109
  changelog/updates/2025-03-17-ca-certificates-3.109-update.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/Manifest
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.109.ebuild
Labels: lts

#2742 Upgrade Linux Kernel for flatcar-3510 from 5.15.177 to 5.15.179
  changelog/updates/2025-03-14-linux-5.15.179-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.179.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.179.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.179.ebuild
Labels: lts

#2638 Pass image version to kola
  ci-automation/vendor-testing/aws.sh
  ci-automation/vendor-testing/azure.sh
  ci-automation/vendor-testing/brightbox.sh
  ci-automation/vendor-testing/digitalocean.sh
  ci-automation/vendor-testing/equinix_metal.sh
  ci-automation/vendor-testing/gce.sh
  ci-automation/vendor-testing/hetzner.sh
  ci-automation/vendor-testing/openstack.sh
  ci-automation/vendor-testing/qemu.sh
  ci-automation/vendor-testing/qemu_update.sh
  ci-automation/vendor-testing/vmware.sh
  sdk_container/.repo/manifests/mantle-container
Labels: main

#2642 Pass image version to kola
  ci-automation/vendor-testing/aws.sh
  ci-automation/vendor-testing/azure.sh
  ci-automation/vendor-testing/brightbox.sh
  ci-automation/vendor-testing/digitalocean.sh
  ci-automation/vendor-testing/equinix_metal.sh
  ci-automation/vendor-testing/gce.sh
  ci-automation/vendor-testing/hetzner.sh
  ci-automation/vendor-testing/openstack.sh
  ci-automation/vendor-testing/qemu.sh
  ci-automation/vendor-testing/qemu_update.sh
  ci-automation/vendor-testing/vmware.sh
  sdk_container/.repo/manifests/mantle-container
Labels: lts

#2641 Pass image version to kola
  ci-automation/vendor-testing/aws.sh
  ci-automation/vendor-testing/azure.sh
  ci-automation/vendor-testing/brightbox.sh
  ci-automation/vendor-testing/digitalocean.sh
  ci-automation/vendor-testing/equinix_metal.sh
  ci-automation/vendor-testing/gce.sh
  ci-automation/vendor-testing/hetzner.sh
  ci-automation/vendor-testing/openstack.sh
  ci-automation/vendor-testing/qemu.sh
  ci-automation/vendor-testing/qemu_update.sh
  ci-automation/vendor-testing/vmware.sh
  sdk_container/.repo/manifests/mantle-container
Labels: stable

#2778 Pass image version to kola
  ci-automation/vendor-testing/aws.sh
  ci-automation/vendor-testing/azure.sh
  ci-automation/vendor-testing/brightbox.sh
  ci-automation/vendor-testing/digitalocean.sh
  ci-automation/vendor-testing/equinix_metal.sh
  ci-automation/vendor-testing/gce.sh
  ci-automation/vendor-testing/hetzner.sh
  ci-automation/vendor-testing/openstack.sh
  ci-automation/vendor-testing/qemu.sh
  ci-automation/vendor-testing/qemu_update.sh
  ci-automation/vendor-testing/vmware.sh
  sdk_container/.repo/manifests/mantle-container
Labels: beta

#2779 Pass image version to kola
  ci-automation/vendor-testing/aws.sh
  ci-automation/vendor-testing/azure.sh
  ci-automation/vendor-testing/brightbox.sh
  ci-automation/vendor-testing/digitalocean.sh
  ci-automation/vendor-testing/equinix_metal.sh
  ci-automation/vendor-testing/gce.sh
  ci-automation/vendor-testing/hetzner.sh
  ci-automation/vendor-testing/openstack.sh
  ci-automation/vendor-testing/qemu.sh
  ci-automation/vendor-testing/qemu_update.sh
  ci-automation/vendor-testing/vmware.sh
  sdk_container/.repo/manifests/mantle-container
Labels: alpha

#2766 cpio: do not fail on ghost rootfs
  build_library/extract-initramfs-from-vmlinuz.sh
Labels: main
