Repository flatcar/scripts, pull requests merged in 2025-10, with the labels that each got.

#3313 sys-apps/systemd: Bump systemd v257.7 in base image
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/sdk/package.accept_keywords
Labels: main

#3336 Upgrade Linux Kernel for main from 6.12.49 to 6.12.50
  changelog/updates/2025-10-03-linux-6.12.50-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.12.50.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.12.50.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.12.50.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.12.50.ebuild
Labels: main

#3323 ci-automation/release.sh: Fix upload to R2
  ci-automation/release.sh
Labels: alpha, main

#3324 Bump sys-block/open-iscsi on stable
  changelog/updates/2025-10-02-update-iscsi.md
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/Manifest
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/open-iscsi-2.1.10-r1.ebuild
  sdk_container/src/third_party/portage-stable/sys-block/open-iscsi/open-iscsi-2.1.11.ebuild
Labels: stable

#3351 Add hvf acceleration support for macOS
  build_library/qemu_template.sh
  changelog/bugfixes/2025-10-08-macos-hvf-accel.md
Labels: alpha, lts, beta, stable, main
