Repository flatcar/scripts, pull requests merged in 2025-05, with the labels that each got.

#2869 Upgrade Linux Kernel for flatcar-4081 from 6.6.88 to 6.6.89
  changelog/updates/2025-05-02-linux-6.6.89-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.89.ebuild
Labels: lts

#2866 Upgrade Linux Kernel for flatcar-4284 from 6.6.88 to 6.6.89
  changelog/updates/2025-05-02-linux-6.6.89-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.89.ebuild
Labels: alpha

#2868 Upgrade Linux Kernel for flatcar-4230 from 6.6.88 to 6.6.89
  changelog/updates/2025-05-02-linux-6.6.89-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.89.ebuild
Labels: beta

#2867 Upgrade Linux Kernel for main from 6.6.88 to 6.6.89
  changelog/updates/2025-05-02-linux-6.6.89-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.89.ebuild
Labels: main

#2870 Upgrade Linux Kernel for flatcar-3510 from 5.15.180 to 5.15.181
  changelog/updates/2025-05-02-linux-5.15.181-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.181.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.181.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.181.ebuild
Labels: lts

#2865 Upgrade Linux Kernel for flatcar-4152 from 6.6.88 to 6.6.89
  changelog/updates/2025-05-02-linux-6.6.89-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.89.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.89.ebuild
Labels: stable

#2886 pkg-auto: Fix occurences generation
  pkg_auto/impl/pkg_auto_lib.sh
Labels: main

#2300 Upgrade Linux kernel from 6.6 to 6.12
  changelog/updates/2025-04-25-kernel-6.12.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/files/hv_fcopy_uio_daemon.service
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.12.20.ebuild
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.12.20.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.12.20.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/amd64_defconfig-6.12
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/arm64_defconfig-6.12
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.12
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.12.20.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.12/z0001-kbuild-derive-relative-path-for-srctree-from-CURDIR.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.12/z0002-pahole-support-reproducible-builds.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.12/z0003-Revert-x86-boot-Remove-the-bugger-off-message.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.12/z0004-efi-add-an-efi_secure_boot-flag-to-indicate-secure-b.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.12/z0005-efi-lock-down-the-kernel-if-booted-in-secure-boot-mo.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.12/z0006-mtd-disable-slram-and-phram-when-locked-down.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.12/z0007-arm64-add-kernel-config-option-to-lock-down-when.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.12/z0008-tools-hv-fix-cross-compilation-for-ARM64.patch
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0002-revert-pahole-flags.patch
Labels: main

#2908 overlay afterburn: update to 5.8.2
  changelog/security/2025-05-14-afterburn-5.8.2.md
  changelog/updates/2025-05-14-afterburn-5.8.2.md
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/afterburn-5.8.2.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/afterburn-9999.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/files/0001-Revert-remove-cl-legacy-feature.patch
  sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/files/0004-build-deps-bump-openssl-from-0.10.66-to-0.10.70.patch
  sdk_container/src/third_party/coreos-overlay/coreos/user-patches/coreos-base/afterburn/tormath1-proxmox.patch
Labels: main

#2798 Add nvidia-drivers sysext
  .github/workflows/portage-stable-packages-list
  build_image
  build_library/extra_sysexts.sh
  build_library/prod_image_util.sh
  build_library/sysext_prod_builder
  build_packages
  build_sysext
  changelog/changes/2025-05-13-nvidia-sysext.md
  changelog/changes/2025-05-13-oot-module-signing.md
  ci-automation/base_sysexts.sh
  ci-automation/image_changes.sh
  sdk_container/src/third_party/coreos-overlay/coreos-base/coreos/coreos-0.0.1.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/x11-drivers/nvidia-drivers
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/make.defaults
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use.mask
  sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers-service/files/bin/install-nvidia
  sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers-service/files/bin/setup-nvidia
  sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers-service/files/nvidia-metadata
  sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers-service/files/units/nvidia.service
  sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers-service/nvidia-drivers-service-535.230.02.ebuild
  sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers-service/nvidia-drivers-service-570.86.15.ebuild
  sdk_container/src/third_party/portage-stable/acct-user/nvpd/metadata.xml
  sdk_container/src/third_party/portage-stable/acct-user/nvpd/nvpd-0-r2.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/Manifest
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/95-nvidia-settings-r1
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-390.conf
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-470.conf
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-545.conf
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-570.conf
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-drivers-390.154-clang15-x86.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-drivers-390.154-clang15.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-drivers-470.141.03-clang15.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-drm-outputclass-390.conf
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-kernel-module-source-515.86.01-raw-ldflags.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-modprobe-390.141-uvm-perms.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-persistenced.confd
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-persistenced.initd
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-powerd.initd
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-settings-390.141-fno-common.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-settings-390.144-desktop.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-settings-390.144-no-gtk2.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-settings-390.144-raw-ldflags.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/nvidia-settings-530.30.02-desktop.patch
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/files/system-sleep.elogind
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/metadata.xml
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-390.157.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-470.256.02-r2.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-535.230.02.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-535.247.01.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-550.144.03.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-550.163.01.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-570.123.07.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-570.124.04.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-570.133.07.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-570.144.ebuild
  sdk_container/src/third_party/portage-stable/x11-drivers/nvidia-drivers/nvidia-drivers-575.51.02.ebuild
Labels: main
