Repository flatcar/scripts, pull requests merged in 2025-07, with the labels that each got.

#3069 Update app-admin/sudo to 1.9.17p1
  changelog/security/2025-07-01-sudo.md
  changelog/updates/2025-07-01-sudo.md
  sdk_container/src/third_party/coreos-overlay/app-admin/sudo/Manifest
  sdk_container/src/third_party/coreos-overlay/app-admin/sudo/sudo-1.9.17_p1.ebuild
Labels: stable

#3078 Upgrade Linux Firmware in main from 20250613 to 20250627
  changelog/updates/2025-07-03-linux-firmware-20250627-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20250627.ebuild
Labels: main

#3102 overlay update_engine: bump to 2025-07-10
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-0.4.10-r25.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-9999.ebuild
Labels: main

#3132 baselayout: fix messagebus user / group ID
  changelog/bugfixes/2025-07-23-baselayout-messagebus-uid.md
  sdk_container/src/third_party/coreos-overlay/sys-apps/baselayout/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-apps/baselayout/baselayout-3.6.8-r18.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-apps/baselayout/baselayout-9999.ebuild
Labels: main

#3128 Upgrade Linux Kernel for flatcar-3510 from 5.15.188 to 5.15.189
  changelog/updates/2025-07-18-linux-5.15.189-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-5.15.189.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-5.15.189.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-5.15.189.ebuild
Labels: lts

#3141 Upgrade Linux Kernel for flatcar-4081 from 6.6.98 to 6.6.100
  changelog/updates/2025-07-25-linux-6.6.100-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.100.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.100.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.100.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.100.ebuild
Labels: lts

#3144 Upgrade Linux Kernel for flatcar-4230 from 6.6.98 to 6.6.100
  changelog/updates/2025-07-25-linux-6.6.100-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.100.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.100.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.100.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.100.ebuild
Labels: stable
