Repository flatcar/scripts, pull requests merged in 2025-09, with the labels that each got.

#3242 update_engine: postinst: Make sure Flatcar extension folder exists
  sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-9999.ebuild
Labels: main

#3294 Upgrade Linux Kernel for flatcar-4230 from 6.6.106 to 6.6.107
  changelog/updates/2025-09-20-linux-6.6.107-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.107.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.107.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.107.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.107.ebuild
Labels: stable

#3309 Upgrade Linux Kernel for main from 6.12.48 to 6.12.49
  changelog/updates/2025-09-26-linux-6.12.49-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.12.49.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.12.49.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.12.49.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.12.49.ebuild
Labels: main

#3289 sys-kernel/coreos-modules: enable CONFIG_MEMCG_V1
  changelog/bugfixes/2025-09-19-kernel-config-memcg-v1.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.12
Labels: alpha, beta, main
