Repository flatcar/scripts, pull requests merged in 2025-04, with the labels that each got.

#2799 Monthly GLSA metadata 2025-04-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202412-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#2676 Mlx5 offload enable
  ci-automation/ci-config.env
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/amd64_defconfig-6.6
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.6
Labels: main

#2846 Simplify and improve flatcar_production_qemu*.sh script
  build_library/qemu_template.sh
Labels: main

#2847 changelog: Add an entry for recent qemu script changes
  changelog/changes/2025-04-24-qemu-script-disks.md
Labels: main

#2848 build_library/qemu_template.sh: Make it use bash
  .github/workflows/portage-stable-packages-list
  build_library/qemu_template.sh
  build_library/vm_image_util.sh
  sdk_container/src/third_party/coreos-overlay/coreos-devel/sdk-depends/sdk-depends-0.0.1-r56.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild
  sdk_container/src/third_party/portage-stable/dev-util/checkbashisms/Manifest
  sdk_container/src/third_party/portage-stable/dev-util/checkbashisms/checkbashisms-2.22.2.ebuild
  sdk_container/src/third_party/portage-stable/dev-util/checkbashisms/checkbashisms-2.23.5.ebuild
  sdk_container/src/third_party/portage-stable/dev-util/checkbashisms/metadata.xml
  sdk_container/src/third_party/portage-stable/perl-core/Getopt-Long/Getopt-Long-2.580.0.ebuild
  sdk_container/src/third_party/portage-stable/perl-core/Getopt-Long/Manifest
  sdk_container/src/third_party/portage-stable/perl-core/Getopt-Long/metadata.xml
  sdk_container/src/third_party/portage-stable/virtual/perl-Getopt-Long/metadata.xml
  sdk_container/src/third_party/portage-stable/virtual/perl-Getopt-Long/perl-Getopt-Long-2.570.0-r1.ebuild
  sdk_container/src/third_party/portage-stable/virtual/perl-Getopt-Long/perl-Getopt-Long-2.580.0.ebuild
Labels: main

#2857 pkg-auto: Add parsing of md5-metadata to aid report generation
  pkg_auto/Makefile
  pkg_auto/download_sdk_and_listings.sh
  pkg_auto/generate_config.sh
  pkg_auto/impl/debug.sh
  pkg_auto/impl/for-shellcheck/README.md
  pkg_auto/impl/for-shellcheck/globals
  pkg_auto/impl/for-shellcheck/version.txt
  pkg_auto/impl/gentoo_ver.sh
  pkg_auto/impl/inside_sdk_container_lib.sh
  pkg_auto/impl/lcs.sh
  pkg_auto/impl/md5_cache_diff_lib.sh
  pkg_auto/impl/md5_cache_lib.sh
  pkg_auto/impl/mvm.sh
  pkg_auto/impl/pkg_auto_lib.sh
  pkg_auto/impl/print_profile_tree.sh
  pkg_auto/impl/util.sh
  pkg_auto/inside_sdk_container.sh
Labels: main

#2839 overlay ue-rs: update to 2025-04-23
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-0.1.0-r11.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-9999.ebuild
Labels: main

#2858 changelog: Add a missing entry for python security fix
  changelog/security/2025-04-29-python.md
Labels: main

#2851 Upgrade Linux Kernel for flatcar-4152 from 6.6.87 to 6.6.88
  changelog/updates/2025-04-26-linux-6.6.88-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.88.ebuild
Labels: stable

#2853 Upgrade Linux Kernel for flatcar-4081 from 6.6.87 to 6.6.88
  changelog/updates/2025-04-26-linux-6.6.88-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.88.ebuild
Labels: lts

#2852 Upgrade Linux Kernel for flatcar-4284 from 6.6.87 to 6.6.88
  changelog/updates/2025-04-26-linux-6.6.88-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.88.ebuild
Labels: alpha

#2855 Upgrade Linux Kernel for main from 6.6.87 to 6.6.88
  changelog/updates/2025-04-26-linux-6.6.88-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.88.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.88.ebuild
Labels: main

#2860 Missing profile changes
  changelog/security/2025-04-38-weekly-updates.md
  changelog/updates/2025-04-28-weekly-updates.md
  sdk_container/src/third_party/coreos-overlay/coreos/config/env/net-dns/bind
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use
  sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use.mask
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.88-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.88-r1.ebuild
Labels: main

#2861 pkg-auto: Mark in-rootfs sysexts as sysexts in reports
  pkg_auto/impl/pkg_auto_lib.sh
Labels: main
