Repository flatcar/scripts, pull requests merged in 2025-02, with the labels that each got.

#2616 Monthly GLSA metadata 2025-02-01
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest
  sdk_container/src/third_party/portage-stable/metadata/glsa/Manifest.files.gz
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-01.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-02.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-03.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-04.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-05.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-06.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-07.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-08.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-09.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-10.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/glsa-202501-11.xml
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.chk
  sdk_container/src/third_party/portage-stable/metadata/glsa/timestamp.commit
Labels: main

#2664 Upgrade Linux Firmware in main from 20250109 to 20250211
  changelog/updates/2025-02-13-linux-firmware-20250211-update.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-firmware/coreos-firmware-20250211.ebuild
Labels: main

#2665 overlay coreos-base: update ue-rs 2025-02-04
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/Manifest
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-0.1.0-r10.ebuild
  sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-9999.ebuild
Labels: main

#2675 Upgrade Linux Kernel for main from 6.6.77 to 6.6.78
  changelog/updates/2025-02-18-linux-6.6.78-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.78.ebuild
Labels: main

#2671 Upgrade Linux Kernel for flatcar-4081 from 6.6.77 to 6.6.78
  changelog/updates/2025-02-18-linux-6.6.78-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.78.ebuild
Labels: lts

#2673 Upgrade Linux Kernel for flatcar-4186 from 6.6.77 to 6.6.78
  changelog/updates/2025-02-18-linux-6.6.78-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.78.ebuild
Labels: beta

#2674 Upgrade Linux Kernel for flatcar-4230 from 6.6.77 to 6.6.78
  changelog/updates/2025-02-18-linux-6.6.78-update.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/hv-daemons/hv-daemons-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/coreos-kernel-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/coreos-modules-6.6.78.ebuild
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/Manifest
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.78.ebuild
Labels: alpha

#2349 sys-kernel/coreos-modules: build Intel iGPU module
  changelog/changes/2024-10-01-enable-intel-igpu-1915-module.md
  sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/amd64_defconfig-6.6
Labels: main

#2667 app-misc/ca-certificates: Account for certs missing newlines
  changelog/bugfixes/2025-02-14-update-ca-certificates-missing-newlines-fix.md
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.108-r1.ebuild
  sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/files/update-ca-certificates
Labels: alpha, lts, beta, stable, main

#2699 setup-nvidia: Modprobe video.ko for amd64
  sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers/files/bin/setup-nvidia
Labels: main

#2696 overlay wa-linux-agent: apply patch to fix ssh public key override issue (stable, beta)
  changelog/bugfixes/2025-02-28-walinuxagent-ignition.md
  sdk_container/src/third_party/coreos-overlay/app-emulation/wa-linux-agent/files/0002-prevent-ssh-public-key-override.patch
  sdk_container/src/third_party/coreos-overlay/app-emulation/wa-linux-agent/wa-linux-agent-2.9.1.1-r3.ebuild
Labels: beta, stable
